progit/progit2

book/07-git-tools/sections/revision-selection.asc
`2^80` should be `2^80^` according to http://powerman.name/doc/asciidoc
=> Fixed display of exponents

book/04-git-server/sections/git-daemon.asc
Progit2 no longer talks about Gitosis so that it is little bit wierd.
=> remove Gitosis

book/04-git-server/sections/git-daemon.asc
Odd grammar introduced when Gitosis was removed in 9f852b8b0ee9dd06066bcb52923a9b913fa9e8fd
=> Fix grammar

book/01-introduction/sections/installing.asc
Additional dependencies required for compiling git from source
https://github.com/progit/progit2/issues/227
=> Installing Git: asciidoc, docbook2x & xmlto #227

Rakefile
To build book, simply run 
```
bundle exec rake
```
=> Default rake task is 'book:build'.

book/06-github/sections/3-maintaining.asc
I saw this typo while going through the material so I figured I would fix it.  I did a quick run through all the other files but nothing else jumped out at me.
=> Fix a typo in Chapter 6, Section 3

book/06-github/sections/3-maintaining.asc, book/06-github/sections/5-scripting.asc, book/07-git-tools/sections/bundling.asc, book/07-git-tools/sections/replace.asc, book/07-git-tools/sections/signing.asc, book/07-git-tools/sections/submodules.asc, book/09-git-and-other-scms/sections/client-tfs.asc, book/C-git-commands/1-git-commands.asc
Hi,
I spotted another rogue possessive while re-reading, so I did a quick search and found the following still lurking.
Regards,
Rob
=> A few it's -> its grammar fixes

book/B-embedding-git/sections/jgit.asc
=> Fix #297: A2.3 shows wrong code to create a repository in JGit

book/02-git-basics/sections/recording-changes.asc, book/04-git-server/sections/git-daemon.asc, book/04-git-server/sections/smart-http.asc, book/07-git-tools/sections/advanced-merging.asc
This PR is a proposal of a few very simple fixes
=> Small set of minor fixes (mainly typo)

book/10-git-internals/sections/packfiles.asc
This is a minor improvement -- if you'd prefer to leave this alone, I'll close this Pull Request.
=> Adjust Line Break

book/10-git-internals/sections/refs.asc
"\`\`refs;''" should be "\`\`refs'';".
=> Adjust Position of Semicolon

book/01-introduction/sections/basics.asc
There is no contradiction, so no "but".
Also, the most past tense is "has been", then "was", then "is".
=> There is no contradiction, so no "but".

book/02-git-basics/sections/recording-changes.asc, book/02-git-basics/sections/viewing-history.asc
Fix issues #340 and #338. Plus, fix a very minor trivial typo.
=> Several Trivial Text Changes

book/04-git-server/sections/git-on-a-server.asc
Redundant since it's preceded by "also".
=> Remove redundant "too" in git-on-a-server.asc

book/03-git-branching/sections/nutshell.asc
The .png file says "The initial commit of my project". This change makes the text match.
=> Match text to text in image.

book/06-github/sections/2-contributing.asc
I originally tripped over "the change we would like to request", which I think is inaccurate/vague. The reason of a pull request is to request the acceptance of a change (where we're the ones providing the change), not to request a change (where the owner of the original project would have to make this change). The rest of the paragraph was also a bit repetitive, so I tried to improve that as well.
=> Edit paragraph in 2-contributing.asc (06-github)

book/06-github/sections/2-contributing.asc
=> Clarify how updating pull requests works

book/06-github/sections/4-managing-organization.asc, book/08-customizing-git/sections/attributes.asc
(one of my biggest pet peeves)
=> Fix capitalization of JavaScript

book/07-git-tools/sections/credentials.asc
similar to the word "e-mail", in the book appears the word "plain-text" in different ways:
plaintext
plain text
plain-text
I just changed the only plaintext.
=> plain-text standardized

book/04-git-server/sections/git-daemon.asc
This was the only issue I found when reviewing console blocks in Chapter 4. 
Hey @ben is this the pattern you prefer or would you rather fewer, larger PRs?
=> Added missing shell prompts to console blocks in git-daemon.asc

book/10-git-internals/sections/refspec.asc
=> Add ini classification to source block in refspec.asc

book/06-github/sections/2-contributing.asc, book/06-github/sections/3-maintaining.asc
This PR cleans up source blocks in Chapter 6. Only a few more to go!
=> Fix console blocks in 06-github

book/07-git-tools/sections/credentials.asc, book/07-git-tools/sections/rerere.asc, book/07-git-tools/sections/reset.asc, book/07-git-tools/sections/rewriting-history.asc, book/07-git-tools/sections/stashing-cleaning.asc, book/07-git-tools/sections/submodules.asc
This PR cleans up source blocks in Chapter 7 and deletes a few lines of whitespace here and there.
=> Fix console blocks in 07-git-tools

book/09-git-and-other-scms/sections/client-hg.asc, book/09-git-and-other-scms/sections/client-tfs.asc, book/09-git-and-other-scms/sections/import-custom.asc, book/09-git-and-other-scms/sections/import-svn.asc
=> Fix console blocks in 09-git-and-other-scms

book/08-customizing-git/sections/attributes.asc, book/08-customizing-git/sections/config.asc, book/08-customizing-git/sections/policy.asc
This PR takes care of Chapter 8.
=> Fix console blocks in 08-customizing.git

book/09-git-and-other-scms/sections/import-hg.asc
The modified `/tmp/authors` file has the last two lines swapped compared to the original file.
=> import-hg.asc: change order of lines

book/10-git-internals/sections/transfer-protocols.asc
Update the explanation to match the response shown in the console block.
=> transfer-protocols.asc: Update the git-receive-pack response explanation

book/07-git-tools/sections/advanced-merging.asc
* Remove multiple "after the fact"
* "merge conflict" -> "resolve conflict
During translation it seems I've found some small issues... Maybe I'm wrong :)
=> Fix small issues in advanced-merging

book/01-introduction/sections/first-time-setup.asc
Signed-off-by: Thomas Ackermann <th.acker@arcor.de>
=> Give more details on Windows system-level config file.

book/06-github/sections/3-maintaining.asc, book/06-github/sections/5-scripting.asc
Fixes two minor typos in chapter 6, the first in the Maintaining section and the second in the Scripting section.
=> Fix typos in Chapter 6

book/08-customizing-git/sections/config.asc
The current link is 404. I also reworded the text to convey the intent of the link, but I'm happy to adjust if there are objections.
=> Correct P4Merge link in "External Merge and Diff Tools"

README.asc
This may help throttle spurious unrelated issues.
=> Add Issue section to Readme

book/02-git-basics/sections/remotes.asc, book/02-git-basics/sections/undoing.asc, book/03-git-branching/sections/remote-branches.asc
Square brackets [] indicate an optional parameters -- use the right ones!
=> Use correct brackets to indicate mandatory/optional parameters

README.asc, book/02-git-basics/sections/recording-changes.asc
I know this is a very small change but i believe that it will be worth is also read the issue:
https://github.com/progit/progit2/issues/511
=> Warning for git commit -a -m""

book/08-customizing-git/sections/policy.asc
Replace fixed string "Chapter 2" to reference to viewing-history.asc like <<_viewing_history>>.
=> Replace "Chapter 2" to reference to viewing-history.asc

book/02-git-basics/sections/undoing.asc
User runs that command, and git does the copy for user.
Fixes #548.
=> Fix issue #548: git checkout command copy the file for you

book/03-git-branching/sections/basic-branching-and-merging.asc
=> Fix issue #448: 3.2 Git Branching -- possibly wrong explanation (upstream vs. downstream)

book/02-git-basics/sections/recording-changes.asc
=> Fix issue #557: Not precise statement for those two columns of `git status -s`

book/04-git-server/sections/git-on-a-server.asc
=> Fix issue #312: /srv/git instead of /opt/git for server repositories

book/05-distributed-git/sections/contributing.asc
=> Fix issue #502: Doubled explanation in one paragraph of 5.2 Contributing..., subsec. Private small team

Gemfile.lock
Make it bundle on OS X with Ruby 2.3 from brew. All files build well on my box.
=> Update json to 1.8.3 and resolve issue #573

book/02-git-basics/sections/recording-changes.asc
=> Fix issue #553: Git does the checkout while cloning, not "you".

book/01-introduction/sections/installing.asc
Fixes #579
Not sure I am do it right, if not, please correct me. Please! :smiley:
=> Fix issue #579: Need autotools for installing git from source

book/03-git-branching/sections/rebasing.asc
Original sentence has  ambiguity . I think the new is better .  I discussed this first at [this google group](https://groups.google.com/forum/?fromgroups=#!topic/git-users/ldQnun-hRtg) . And I accepted Thomas Ferris Nicolaisen's suggestion sentence replaced my original one .
=> chang to more clearly sentence

README.asc, book/02-git-basics/sections/viewing-history.asc, book/05-distributed-git/sections/contributing.asc, book/06-github/sections/5-scripting.asc, book/07-git-tools/sections/submodules.asc, book/08-customizing-git/sections/policy.asc, book/09-git-and-other-scms/sections/import-svn.asc
Several new lines added, one newline deleted, several quotes changes and revert of wrong change of description about "--no-merges" (more details in commit description)
=> Small fixes

book/02-git-basics/sections/getting-a-repository.asc
It's very useful to have example for each OS how to change the directory
in Git (especially for Windows because the syntax is different from the
default syntax — C:/Users/your_repository).
Second try to contribute to this project.
=> Added examples how to change the directory

book/09-git-and-other-scms/sections/import-svn.asc
Beginners often are confused and overwhelmed. Hence it is a good idea to provide even simplest information like "now change into the project directory".
=> Be absolutely clear for beginners

book/03-git-branching/sections/basic-branching-and-merging.asc
Had to reread the sentence to understand it. If I bugged on it, others might as well.
=> Simplify sentence. Construction not obvious for non natives

book/08-customizing-git/sections/hooks.asc
=> Improve possible incomplete sentence in CHAPTER 8: Customizing Git, subsection: Installing a Hook.

book/01-introduction/sections/installing.asc, book/03-git-branching/sections/basic-branching-and-merging.asc, book/07-git-tools/sections/submodules.asc
=> Replace all instances of 'web site' with 'website'

book/07-git-tools/sections/submodules.asc
=> Replace the obscure term 'vendoring' with 'copying'

book/07-git-tools/sections/submodules.asc
=> GIT Submodules section missing a step.

book/A-git-in-other-environments/sections/zsh.asc
Pointed to github repo instead.
=> Fix broken link to git-prompt.sh

book/04-git-server/sections/smart-http.asc
Change 'though' to 'through' in first sentence.
=> Spelling error corrected in Section 4.6

book/05-distributed-git/sections/contributing.asc
While reading the book I noted two places where the text could be improved slightly
=> Two small edits

book/04-git-server/sections/protocols.asc
As far as I could think of the word _based_ would fit better than the word _basic_ in that line I changed in the PR. Correct me, if i'm wrong. 
P.S. : Thanks for such a good book on Git
=> Corrected a little typo in a section

book/04-git-server/sections/git-daemon.asc, book/04-git-server/sections/gitweb.asc, book/04-git-server/sections/protocols.asc, book/04-git-server/sections/setting-up-server.asc, book/04-git-server/sections/smart-http.asc
/srv/git instead of /opt/git for server repositories. Fixed in all of
chapter 4
=> Fixes #312

book/01-introduction/sections/installing.asc
Add paragraph about installing Git using [Chocolatey](https://chocolatey.org) on Windows.
=> Add paragraph about installing Git using Chocolatey

book/01-introduction/sections/installing.asc, book/A-git-in-other-environments/sections/zsh.asc, book/introduction.asc, book/preface.asc
=> removed trailing spaces

book/09-git-and-other-scms/sections/import-bzr.asc
just for a quick review before inclusion.
=> The repo needs a reset after the import from bzr

book/09-git-and-other-scms/sections/client-hg.asc
=> updated Mercurial's URL

book/04-git-server/sections/setting-up-server.asc
Add additional information about chsh command, and simplify the command to change the login shell.
=> Modify command to change git user's login shell

book/02-git-basics/sections/viewing-history.asc
=> added space in git log command example

Rakefile
=> removed an unnecessary space

book/05-distributed-git/sections/contributing.asc
I propose this update to illustrate the use of a really strong password.
=> used a real password for the Gmail account

book/07-git-tools/sections/revision-selection.asc
Also, the full character names "caret" and "tilde" are mentioned.
Resolves https://github.com/progit/progit2/issues/785
=> Ancestry references: note about caret for Windows users

book/05-distributed-git/1-distributed-git.asc, book/05-distributed-git/sections/contributing.asc, book/05-distributed-git/sections/distributed-workflows.asc
Minor tweaks to Chapter 5, including:
- small adjustments to wording
- standardize on <> for replaceable content
- add italics to represent "first term" emphasis
=> Small number of grammar/syntax tweaks to Chapter 5.

book/04-git-server/sections/git-on-a-server.asc, book/04-git-server/sections/protocols.asc, book/04-git-server/sections/setting-up-server.asc, book/04-git-server/sections/smart-http.asc
- Add hyphenation where appropriate
- Standardize on <> for replaceables, [] for optionals
- Add NOTE to mention deprecated FTP/FTPS protocols
- Add NOTE to clarify "--local" clone option
- Add NOTE to mention ssh-copy-id utility for SSH configuration
=> Various font/grammar/clarification tweaks to Chapter 4

book/03-git-branching/sections/basic-branching-and-merging.asc, book/03-git-branching/sections/rebasing.asc, book/03-git-branching/sections/remote-branches.asc
- Some minor grammar rewording
- Adding monospaced font to some commands/filenames
- Standardize on <> for replaceables, [] for optionals
=> Various font/grammar/clarification tweaks to Chapter 3

book/01-introduction/sections/basics.asc, book/01-introduction/sections/command-line.asc, book/01-introduction/sections/first-time-setup.asc, book/01-introduction/sections/help.asc, book/01-introduction/sections/history.asc, book/01-introduction/sections/installing.asc
Tweaks include(among other things):
- some rewording for proper grammar
- adding italics for first-time and emphasis rendering
- adding hyphenation
=> Minor grammar/font/NOTE/clarification tweaks to Chapter 1.

CONTRIBUTING.md
=> CONTRIBUTING.md: one sentence per line

book/02-git-basics/sections/getting-a-repository.asc
Some minor changes to wording and grammar, to get rid of wording
I've always found to be a bit awkward or unclear.
=> Tweak "Getting a Git Repository" section for grammar/wording.

book/01-introduction/sections/about-version-control.asc
- some punctuation changes
- standardize on "--" for em dash
- minor rewording for clarity
- change regular quotes to smart quotes
=> Minor tweaks (wording, punctuation) to "About Version Control"

book/01-introduction/sections/basics.asc
- Some punctuation adjustment
- Rewording for clarity
- Turn run-on paragraph into list
=> Minor tweaks (rewording, punct, adding lists) to "Git Basics"

CONTRIBUTING.md
A lot of questions have been asked. This is the first step to an
instructional manual for translations.
=> Add complimentary instructions and information for translating

book/04-git-server/sections/git-on-a-server.asc
- standardize on " -- " for em dashes
- rewording for grammar/clarity
=> Minor punctuation/font/wording tweaks to "Getting Git on a Server"

.travis.yml
This tells Travis to build the book and stash it in a release every time we merge to `master`.
=> Try out releases on Travis

book/07-git-tools/sections/revision-selection.asc
As usual:
- standardize on " -- " for em dashes
- rewording for clarity
- add a TIP or two
=> General rewording/grammar/font cleanup of "Revision Selection"

book/07-git-tools/sections/searching.asc
- rewording for clarity
- some font changes
- updating search examples to match current Git codebase
=> Minor aesthetic/rewording changes to "Searching" section in Chapter 7

book/07-git-tools/sections/rewriting-history.asc
A moderate amount of rewriting this section for clarity, and adding
a TIP regarding "--no-edit".
=> Minor rewording/grammar tweaks to "Rewriting History"

book/04-git-server/sections/generating-ssh-key.asc, book/09-git-and-other-scms/sections/client-bzr.asc, book/09-git-and-other-scms/sections/client-p4.asc
Corrected three minor typos in section 4.3 and section 9.1:
(1) Removed confusing phrase (That being said) at start of section 4.3
(2) Added missing word (you) in Section 9.1 regarding Bazaar
(3) Changed word (write to wrote) to fix typo in section 9.1 regarding p4
=> Minor typo corrections.

CONTRIBUTING.md
Filipino / Tagalog Translations
=> Added Tagalog Links

book/06-github/sections/1-setting-up-account.asc
The language here is outdated, as GitHub now offers unlimited private repositories with all paid plans. I've tried to keep the messaging as simple as possible – hopefully this is OK! 😅
=> Update information about paid GitHub plans

book/05-distributed-git/sections/contributing.asc
$ git request-pull origin/master myfork should produce commits by Jessica and not by John. Fixed the first appearence of John.
=> Changed John to Jessica in Forked public project

book/10-git-internals/sections/objects.asc
Very miniscule ;)
I couldn't figure out how you deal with such tiny errors. I hope this is alright, just tell me otherwise.
=> Fix small typo

Rakefile, progit.asc
This should partly address #1009
=> Add authors and publication date to the book

book/03-git-branching/sections/workflows.asc
Replaced 'it' with 'them' because it refers to 'workflows' which is in plural.
=> Number consistency

book/A-git-in-other-environments/sections/guis.asc, book/A-git-in-other-environments/sections/powershell.asc
Mention Visual Studio Code within the GUI section, as it is getting more popular these days.
Update for PowerShell 6 (Core) and add cross platform support. Currently the "prompt" function set by Posh-Git in PowerShell Core is a little bugged, but I'm sure they will fix it soonish.
=> Update for PowerShell 6 (Core) and Visual Studio Code

book/01-introduction/sections/installing.asc
PR asked by @jnavila about https://github.com/progit/progit2/issues/1053 and https://github.com/progit/progit2/issues/1054
Closes #1053 
Closes #1054
=> Adjusting documentation #1053 #1054

book/05-distributed-git/sections/maintaining.asc
=> maintaining.asc: standardize on "--" for em dashes, add italics

book/07-git-tools/sections/revision-selection.asc, book/B-embedding-git/sections/go-git.asc
Fix following typos : 
* managemen -> management
* stategy -> strategy
=> Fix minor typos

book/02-git-basics/sections/tagging.asc
=> removed trailing space

.tgitconfig
=> TortoiseGit bug tracker

Rakefile, progit.asc
Hello,
thank you guys for this wonderful book! :-)
With this pull request I'm trying to simplify a little bit `Rakefile`, by using built-in asciidoctor attributes for revision and date (introduced by eff61943be). Please let me know what do you think about it.
=> inject version and date using attributes

book/04-git-server/sections/generating-ssh-key.asc, book/04-git-server/sections/git-daemon.asc, book/04-git-server/sections/git-on-a-server.asc, book/04-git-server/sections/protocols.asc, book/04-git-server/sections/setting-up-server.asc, ch04-git-on-the-server.asc
Just minor cleanup and clarification in all of Chapter 4.
=> chapter 4: numerous tweaks, rewordings and font changes

book/05-distributed-git/sections/distributed-workflows.asc
=> chapter 5: semantic cleanup of first part of chapter 5

book/03-git-branching/sections/nutshell.asc
=> Branching: Add a note about "git checkout -b"

book/01-introduction/sections/installing.asc
Signed-off-by: Junjie Yuan <junjieyuanxiling@gmail.com>
=> HTTP->HTTPS

A-git-in-other-environments.asc
I made a spelling error, I only saw this after you've merged it into master.... :worried: 
It's supposed to be ``include`` not ``included``. The other lines all use ``include``, so I was in the wrong here.
=> Fix spelling error.

book/introduction.asc
=> Minor rewrite to account for changes in Appendix A.

TRANSLATING.md
@ben I've fixed some spelling and https issues here.
While fixing the issues, I noticed that the style of the text is not in line with the rest of the text in the book and on the rest of the progit2 source. Maybe this needs a rewrite or editing pass?
=> Fix some spelling and https issues for translating.md

book/01-introduction/sections/installing.asc, book/02-git-basics/sections/getting-a-repository.asc, book/04-git-server/sections/generating-ssh-key.asc, book/04-git-server/sections/git-on-a-server.asc, book/08-customizing-git/sections/attributes.asc, book/08-customizing-git/sections/config.asc, book/A-git-in-other-environments/sections/guis.asc
completes #1161 and fixes #1197
=> Mac → macOS

TRANSLATING.md
@jnavila This project seems to have some recent work done on it. Do you want to mention it in the translating.md file?
The project is listed on the git-scm page: https://git-scm.com/book/fa/v2
=> Add Persian translation project.

TRANSLATING.md
Hi @jnavila, this adds the Arabic translation to the table.
There doesn't seem to be all that much happening in that repository though. On the introduction only a part is translated, so this needs a lot more work before it's in a state that it can be pushed to the git-scm page. (https://github.com/progit2-ar/progit2/blob/master/book/01-introduction/1-introduction.asc)
Are you sure you actually want this listed?
Reference: #468
=> Add Arabic translation.

TRANSLATING.md
=> Add Bulgarian translation project.

book/06-github/sections/2-contributing.asc
Emojis are not really "incredibly useful"...
=> Revert "one typo fixed" (6b82548b)

book/01-introduction/sections/what-is-git.asc
"1.3 Getting Started - What is Git?" - "The Three States", the orders of "modified", "staged" and "committed" were mixed and I think it might be better to be all the same natural order.
=> Change the order of the three states of files.

C-git-commands.asc
Following #1269 & #1270, it was suggested to me to include improve the table in these two ways, see commits & diff. Do you think that makes sense?
=> Expand core.editor command list in Appendix

C-git-commands.asc
From https://github.com/xi-editor/xi-mac/tree/fb9f67e8061490027671793d1fa8287b49f5c4c9#git-editor.
=> Add Xi to core.editor list in Appendix

book/04-git-server/sections/setting-up-server.asc
=> preventing SSH port forwarding

book/01-introduction/sections/about-version-control.asc
=> Added link to GNU RCS

book/07-git-tools/sections/submodules.asc
=> Add cd commands to clarify "Working on a submodule" section

C-git-commands.asc
I overlooked this in 5084cfebaadbe68d71378a99e15f31097ba784ed, sorry!
=> Correct command formatting in core.editor appendix table

C-git-commands.asc
See diff & https://github.com/progit/progit2/issues/1269 ;-)
=>  Add macOS' TextEdit to core.editor list in Appendix

book/01-introduction/sections/installing.asc
=> installing: git version 2.8.0 is used

book/A-git-in-other-environments/sections/powershell.asc
for unicity and consistency of the book's index
"PowerShell" is the official spelling.
=> PowerShell

book/05-distributed-git/sections/distributed-workflows.asc, book/07-git-tools/sections/submodules.asc
So that no gender is implied in this sentence and the explanation makes sense for people of all genders.
(I did not open an issue as the contributing guidelines request, as the change is very small)
=> Use “their” instead of “his”

TRANSLATING.md
=> Add pointer to Swedish translation

book/04-git-server/sections/protocols.asc
I was just thinking that adding a link, explaining what NFS stands for, would be helpful.
=> NFS clarification

README.asc
Hopefully this will help anyone else that is unfamiliar with AsciiDoc, like I was.
While I was at it, I also changed the capitalization to AsciiDoc, which appears to be the official stylized capitalization. (https://www.google.com/search?q=asciidoc)
=> Adding an Asciidoc quick reference

C-git-commands.asc
Found on https://www.mobilefish.com/developer/git/git_quickguide_commands.html, but maybe @IDMComputerSolutions can verify?
=> Add UltraEdit to core.editor list in Appendix

book/10-git-internals/sections/maintenance.asc
Rationale: "However" would start a contradiction, while there is a simple implication, so "so" or "therefore" needs to be used.
Hopefully I didn't misunderstand the text and the suggested correction is OK... :)
=> Fix sentence flow: not "however", but "so"

book/A-git-in-other-environments/sections/powershell.asc
The previous link lead to a 404-page
=> Updated link to PowerShell Gallery overview

book/06-github/sections/1-setting-up-account.asc
=> Colobarators limit has been removed for free plan

book/01-introduction/sections/installing.asc
@mo-gul proposed this [while working on the german translation](https://github.com/progit/progit2-de/pull/110). I agree that using code highlighting would be nice in this sentence. What do you think?
=> Use code highlighting

book/02-git-basics/sections/aliases.asc
Merging this pull request fixes #1453
This pull-request contains the improved text that @Ben has proposed: https://github.com/progit/progit2/issues/1453#issuecomment-652650434
=> Improve intro text on aliases

book/08-customizing-git/sections/config.asc
This pull-request changes the auto-correct message to the one in git 2.25.1.
=> Update git auto-correct message

book/05-distributed-git/sections/contributing.asc
- Fix spelling
Fixes the bad spelling introduced by me in #1489.
=> Fix spelling

.github/pull_request_template.md
=> Fix an article

Gemfile
- Pin dependencies so all contributors are on the same version of dependencies.
Hi @jnavila, I think it's a good idea to pin our dependencies as well.
This will ensure we're both on the same version of everything.
I did a `bundle install` from your current branch, and noted the installed versions in the Gemfile.
This also ensures that our builds are reproducible.
=> Pin dependencies

book/02-git-basics/sections/undoing.asc
=> Fix typo in section 2.4

Rakefile
- Exclude `dependabot[bot]` user from contributors list
=> Exclude dependabot from contributors list

book/01-introduction/sections/help.asc
- Update `git add -h` output, based on Git version 2.32.0
I'm not fixing a GitHub issue with this pull request.
=> Update `git add -h` output, based on Git version 2.32.0

book/01-introduction/sections/help.asc
The #git channel on Freenode does not have an active user base anymore.
Match the recommended IRC network of <https://git-scm.com/community>.
-
=> Point readers to Libera Chat IRC

book/01-introduction/sections/history.asc
- minor tweak to obsolete wording of early history description
Fixes #1675.
=> Correct description of Linux kernel maintenance history

book/02-git-basics/sections/recording-changes.asc
- Make it clear that the set of tracked files includes more than those in the latest commit.
=> Fix descriptions of untracked files

book/03-git-branching/sections/branch-management.asc
=> Fix typo in console example

book/01-introduction/sections/installing.asc
Rephrased the version note to merely recommend a recent 2 version
without singling out a specific version.
Following discussion in #1731 
-
=> Remove specific minimum version

.github/workflows/release-on-merge.yml, .gitignore, Gemfile, Rakefile
- Add generation of FB2 document
=> Add FB2 output

book/04-git-server/sections/hosted.asc, book/06-github/sections/3-maintaining.asc, book/07-git-tools/sections/credentials.asc, book/07-git-tools/sections/submodules.asc, book/07-git-tools/sections/subtree-merges.asc
=> Fix minor issues

book/01-introduction/sections/installing.asc, book/09-git-and-other-scms/sections/client-bzr.asc
- Some links are changed
- http://bazaar.canonical.com  
-> http://bazaar.canonical.com
- https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F  
-> https://docs.fedoraproject.org/en-US/epel/#how_can_i_use_these_extra_packages
=> Update changed links

TRANSLATING.md
- This fixes 3 redirected URLs and adds one missing closing bracket in the translating docs.
=> Update URLs and fix closing bracket in TRANSLATING

book/01-introduction/sections/installing.asc, book/06-github/sections/2-contributing.asc
- This adds two caret shorthands to the URL in the installation and contributing chapters so they open in new tabs
- The GitHub mirror URL for Git repository points to empty releases page. Probably the URL with tags might be better.
=> Use caret shorthand and tags URL

book/01-introduction/sections/about-version-control.asc, book/01-introduction/sections/installing.asc, book/01-introduction/sections/what-is-git.asc, book/03-git-branching/sections/rebasing.asc, book/03-git-branching/sections/remote-branches.asc, book/05-distributed-git/sections/maintaining.asc, book/06-github/sections/1-setting-up-account.asc, book/06-github/sections/2-contributing.asc, book/06-github/sections/3-maintaining.asc, book/06-github/sections/5-scripting.asc
- This syncs some remaining images to not have ending dot.
- And some image captions were synced with alt tags.
=> Sync image alt descriptions with captions

book/01-introduction/sections/history.asc, book/04-git-server/sections/protocols.asc
- Sentences inside brackets are lowercased elsewhere in the book, so this syncs the same capitalization also on two remaining places.
=> Use lowercase

C-git-commands.asc
Add The rust based editor Helix to `git config core.editor` commands in Git Commands - Setup and Config
=> Add The rust based editor Helix to git config core.editor commands in Git Commands - Setup and Config

TRANSLATING.md, book/02-git-basics/sections/remotes.asc, book/09-git-and-other-scms/sections/import-bzr.asc, book/10-git-internals/sections/refs.asc, book/A-git-in-other-environments/sections/jetbrainsides.asc, book/A-git-in-other-environments/sections/powershell.asc, book/A-git-in-other-environments/sections/sublimetext.asc, book/A-git-in-other-environments/sections/visualstudiocode.asc, book/A-git-in-other-environments/sections/zsh.asc, book/B-embedding-git/sections/dulwich.asc
- This syncs the word "Git" a bit more across the book.
=> Capitalize Git

book/07-git-tools/sections/revision-selection.asc
- One closing bracket fixed to go out of highlighted code section and sentence lines synced.
=> Fix closing bracket

book/07-git-tools/sections/rerere.asc
- This adds 3 missing image captions in the Rerere section.
=> Add image captions in Rerere section

book/07-git-tools/sections/reset.asc
- This adds some missing captions for the images in Reset Demystified section
=> Add image captions in Reset Demystified section

book/03-git-branching/sections/branch-management.asc
- Instead of inline copied section title, this one uses the cross reference.
=> Add cross reference for changing master

book/02-git-basics/sections/viewing-history.asc, book/03-git-branching/sections/rebasing.asc, book/05-distributed-git/sections/maintaining.asc, book/06-github/sections/2-contributing.asc, book/06-github/sections/3-maintaining.asc, book/07-git-tools/sections/credentials.asc, book/07-git-tools/sections/reset.asc, book/07-git-tools/sections/rewriting-history.asc, book/07-git-tools/sections/stashing-cleaning.asc, book/07-git-tools/sections/submodules.asc, book/08-customizing-git/sections/hooks.asc, book/09-git-and-other-scms/sections/client-bzr.asc, book/09-git-and-other-scms/sections/client-hg.asc, book/09-git-and-other-scms/sections/client-p4.asc, book/10-git-internals/sections/maintenance.asc, book/10-git-internals/sections/objects.asc, book/10-git-internals/sections/transfer-protocols.asc, book/A-git-in-other-environments/sections/guis.asc, book/A-git-in-other-environments/sections/sublimetext.asc, book/A-git-in-other-environments/sections/zsh.asc, book/B-embedding-git/sections/jgit.asc
- Add more text formatting to some remaining places.
=> Add more text formatting

status.json
- This adds few missing files to status.json file. Although, this is probably not utilized at the moment it might be useful for possible future translations to have an overview.
=> Add missing status sections

book/04-git-server/sections/protocols.asc, book/06-github/sections/1-setting-up-account.asc, book/07-git-tools/sections/advanced-merging.asc, book/09-git-and-other-scms/sections/import-hg.asc, book/09-git-and-other-scms/sections/import-svn.asc
- Fix few case sensitivity of letters.
- One possible grammatical fix.
=> Fix grammar and letter case

book/01-introduction/sections/first-time-setup.asc, book/02-git-basics/sections/viewing-history.asc, book/09-git-and-other-scms/sections/import-custom.asc, book/10-git-internals/sections/environment.asc, book/dedication.asc, book/introduction.asc
- In the content one line per sentence is used everywhere so this syncs few remaining ones as well.
=> Fix one sentence per line

book/03-git-branching/sections/nutshell.asc
- This uses the same recommendation for commit messages on few remaining places as on most of the commits in the book (imperative and first letter uppercase).
=> Sync commit messages

Rakefile
- Fix the file name in the `clean` task
=> Fix invalid file name on cleanup

book/07-git-tools/sections/replace.asc
- This adds few more missing image captions in the Replace section.
=> Add image captions in Replace section

Rakefile
- Added sort to contributors list as in the [progit2-pub](https://github.com/progit/progit2-pub) Rakefile. This sorts contributors alphabetically also for the users with only usernames.
- ~~Improved contributors title a bit.~~ Edit: title is ok, my bad, commit fixed.
=> Improve contributors list

Rakefile
- This adds another file to the clean command - progit-kf8.epub.
=> Add progit-kf8.epub to clean step

book/01-introduction/sections/about-version-control.asc, book/01-introduction/sections/what-is-git.asc, status.json
- removed the mentions to Bazaar since Bazaar is dead
- updated status.json
In #1901, I removed the parts related to Bazaar. We have to remove the remaining parts talking about Bazaar.
=> no longer mention Bazaar following #1901

C-git-commands.asc
=> Fix for Helix editor

book/07-git-tools/sections/submodules.asc
- [ x ] I provide my work under the [project license](https://github.com/progit/progit2/blob/main/LICENSE.asc).
- [ x ] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).
I think `and then` would be better changed to `and when later` or `and when (later)` to better clarify the purpose (I got confused the first time).
> ... 
Then you need to tell Git what to do if you have made changes and **when later** `git submodule update --remote` pulls in new work from upstream.
My change is on `Git Tools/Submodules/Working on a Project with Submodules/Working on a Submodule`
=> Simple clarification

images/rerere1.svg
- Fixed typo in a rerere figure
=> Fixed: Typo in rerere1.svg

book/07-git-tools/sections/submodules.asc
- Add "from the main project" for clarity.
Because of the `cd DbConnector/` in the previous code section, it was unclear which location to run the `git submodule init` and `git submodule update` commands.
=> Minor clarification
