book/06-github/sections/2-contributing.asc

Changed "an project" to "a project".

Fix tiny article typo

---

book/01-introduction/sections/about-version-control.asc

"Clone" is more accurate than "checkout" for the context here. (see https://github.com/progit/progit2/issues/226)

[about-version-control.asc] change "checkout" to "clone"

---

book/07-git-tools/sections/revision-selection.asc

found this while reading, thanks for this nice book!

small grammar fix: it have -> it has

---

book/02-git-basics/sections/viewing-history.asc

As noted in #237 this fixes the typo for --date option.

Replace dash with two hyphens for author date

---

book/10-git-internals/sections/maintenance.asc

The `filter-branch` example errors out ('Unknown option ignore-unmatch') if the `--ignore-unmatch` flag does not come before the `--cached` flag.

Fix order of `git rm` options

---

book/07-git-tools/sections/reset.asc

The SHA-1 of `file.txt` in the diagrams is `9e5e6a4` but the text refers to `9e5e64a`.  Since I'm assuming either hash is fine, I've fixed the text to match the diagram since I figure that's an easier change.

Fix SHA-1 of file.txt v2 to match diagrams

---

book/07-git-tools/sections/advanced-merging.asc
book/C-git-commands/1-git-commands.asc

The explanation for -Xignore-space-change and -Xignore-all-space options
was a bit reformulated.
And for most programming languages use of the -Xignore-space-change
option while merging could be more suitable than that of
the -Xignore-all-space option because it prevents different
lexemes from concatenating together (e.g. "def hello" and "defhello").

Advanced merging: use -Xignore-space-change

---

book/02-git-basics/sections/tagging.asc

I got confused at first with the branch name being 'version'. So here I just added the meta-syntax to clarify the abstract form;
```
git checkout -b [branchname] [tagname]
````
is the same as the specific concrete form;
````
$ git checkout -b version2 v2.0.0
````

Tagging: Add code description with variables.

---

book/07-git-tools/sections/searching.asc

Just a minor typo spotted at the beginning of the Searching section of Chapter 7.

Grammar fix: possessive for contraction

---

book/01-introduction/sections/installing.asc

Using the commands in the book, e.g
```
$ apt-get install git
```
Leaves an error message unfriendly to newbies and not evening mentioning sudo.
```bash
0 jan@osprey:~$apt-get install git
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
100 jan@osprey:~$
```

sudo add sudo

---

book/05-distributed-git/sections/contributing.asc
book/07-git-tools/sections/subtree-merges.asc

The use of the --no-commit option together with the --squash option
is redundant since according to the manual git merge --squash doesn't
automatically make commit after merging.

git merge use: --squash doesn't need --no-commit

---

book/05-distributed-git/sections/contributing.asc
book/C-git-commands/1-git-commands.asc

`git send-email` does not put the patches into an IMAP folder, but the
command `git imap-send`.
I've changed the command and added the output that occurs when using the
imap-send command. I also wrote a short sentence to make use of the previous
output used in the document, plus I added an example for an SMTP config.
Added `git imap-send` to the section email of git commands.

fixed error in the imap section

---

book/02-git-basics/sections/aliases.asc

Quotation marks doesn't work in the example on Git 1.9.5 on Windows 7. Only works with apostrophes.
Error:
Alexandre@MICROBOARD ~/projecs/ticgit (master)
$ git config --global alias.visual "!gitk"
sh.exe": !gitk: event not found
But:
Alexandre@MICROBOARD ~/projecs/ticgit (master)
$ git config --global alias.visual '!gitk'
Alexandre@MICROBOARD ~/projecs/ticgit (master)
$ git config alias.visual
!gitk

Example doesn't work on Windows 7.

---

book/08-customizing-git/sections/attributes.asc

git archive uses git log's `pretty=format:` processor directly, and
strips the surrounding `$Format:` and `$` markup from the output.

export-subst uses git log's custom formatter

---

book/03-git-branching/sections/remote-branches.asc

Also added some text to introduce remote references. Ref. #301.

Several "remote branch" should be "remote-tracking branch".

---

book/07-git-tools/sections/submodules.asc

Example: ../sibling.git
This is very helpful when server name changes depending on your location, or when repo is cloned using a fake hostname for any reason

git supports relative submodules URLs

---

book/03-git-branching/sections/rebasing.asc

The gender-neutral pronoun 'they' is used many times in the text except in the following sentence :
`that's why she rebased in the first place.`

use of gender-neutral pronoun 'they'

---

book/03-git-branching/sections/rebasing.asc

`Now, someone else does more work that includes a merge, and pushes that work to the central server.`
In the previous sentence, we talk about the work done by another developer, not about their implicit commits.

fix bad subject

---

book/04-git-server/sections/protocols.asc

This commit is a proposal to insert as file:// cons the fact than damaging such repo is quite easy compared to other protocols.
Anyone can operate a rm -rf /* by mistake on its computer and delete mounted repository.

file:// repos are often easier to damage by mistake

---

book/10-git-internals/sections/transfer-protocols.asc

I found the best way to fix the error is correcting the numbers, so I did it.

fixed number error in transfer-protocols example

---

book/02-git-basics/sections/recording-changes.asc

There are few places in `book/02-git-basics/sections/recording-changes.asc` where rule mentioned in title of this PR is not fallowed. This PR fixes that, because "one sentence per line" is very helpful for translators :)

New line should separate sentences (02-git-basics/sections/recording-changes.asc)

---

book/02-git-basics/sections/undoing.asc

Text uses "git add *", whereas the following example uses "git add .".
I chose "git add *" for both, but it looks like either is correct. See also http://stackoverflow.com/questions/26042390/git-add-asterisk-vs-git-add-period and http://stackoverflow.com/questions/16969768/what-does-git-add-git-add-single-dot-command-do.

Bring text and example in line in undoing.asc

---

book/02-git-basics/sections/recording-changes.asc

1. We add 'test line' without a sharp sign and following git diff shows it with the sharp sign. It should be consistent.
2. Ignore rule doc/**/*.txt overrides doc/*.txt, so let's change to something clear.

Small confusing moments

---

book/03-git-branching/sections/basic-branching-and-merging.asc
book/03-git-branching/sections/nutshell.asc
book/03-git-branching/sections/rebasing.asc
book/03-git-branching/sections/remote-branches.asc
book/03-git-branching/sections/workflows.asc

Branch names are currently not consistently highlighted. This fixes some of them.

Highlight some branch names

---

book/10-git-internals/sections/refspec.asc

- All branch names is monospaced.
- Remove an extra whitespace.

Fix Monospace Issue in 10-git-internals refspec

---

book/07-git-tools/sections/advanced-merging.asc

Update quoted branch names by monospaced names in this section.

Fix Monospace Issue in 07-git-tools advanced-merging

---

book/09-git-and-other-scms/sections/import-tfs.asc

With Git for Windows (https://msysgit.github.io/), folloing command
> PS C:\tmp\src\git\pullreq> git filter-branch -f --msg-filter 'sed "s/^git-tfs-id:.*$//g"' -- --all
gets following error message:
> usage: git core\git-filter-branch [--env-filter <command>] [--tree-filter <command>]
>  ...
Command line argument '--' should be quoted like:
> PS C:\tmp\src\git\pullreq> git filter-branch -f --msg-filter 'sed "s/^git-tfs-id:.*$//g"' '--' --all
and output message will be like this:
> Rewrite c9cea454ab929f2db984184647b9da9cc581abde (8/8)
> ...

Correct "git filter-branch" command line argument on PowerShell

---

book/04-git-server/sections/smart-http.asc

It obviously should be .htpasswd not .htaccess here

fix a typo: .htaccess instead of .htpasswd

---

book/01-introduction/sections/installing.asc
book/04-git-server/sections/generating-ssh-key.asc

Git for Windows 2.5.0.**windows**.1 is released.
And the website is switched to https://git-for-windows.github.io/, see [GfW issue #12](https://github.com/git-for-windows/git/issues/12).
I think it's time to drop the "msysgit" totally in this book.
/cc @dscho

Use "Git for Windows" instead of "msysgit"

---

book/01-introduction/sections/first-time-setup.asc

Further explain the real "/etc/gitconfig" file path when using Git for Windows 2.x

---

book/02-git-basics/sections/getting-a-repository.asc
book/02-git-basics/sections/recording-changes.asc

Trivial change: I noticed a few paragraphs describing [source,console] blocks that were not preceded by colon.

Nearly every other [source,console] section was preceded by a colon

---

book/01-introduction/sections/installing.asc

A number of [source,console] blocks in the 01-Introduction chapter weren't subject to syntax highlighting as they should have been. This PR makes the impacted blocks consistent with the rest of the section.

Updated installing.asc to make [source,console] blocks consistent

---

book/02-git-basics/sections/viewing-history.asc

This was the only issue I found when reviewing the console blocks in Chapter 2.

Add missing shell prompt to console block

---

book/05-distributed-git/sections/contributing.asc
book/05-distributed-git/sections/maintaining.asc

Fixed one source,console block in maintaining.asc that wasn't being highlighted and made all block start and end markers consistent with the rest of the book.

Fix console blocks in 05-distributed-git

---

book/07-git-tools/sections/revision-selection.asc

The fourth dot isn't part of the SHA-1, but ends the sentence.

revision-selection.asc: Small typographic change

---

book/06-github/sections/2-contributing.asc
book/07-git-tools/sections/advanced-merging.asc
book/07-git-tools/sections/reset.asc
book/07-git-tools/sections/signing.asc
book/10-git-internals/sections/refs.asc
book/C-git-commands/1-git-commands.asc

Found them with a regexp '[a-z]  [a-z]' and hand-picked them so
the command line outputs don't get affected.

remove unneeded double whitespaces

---

book/06-github/sections/5-scripting.asc

The only place in the whole book where there was a colon before
the link (at: http:// --> at http://).

remove a colon before a link

---

book/02-git-basics/sections/undoing.asc
book/03-git-branching/sections/rebasing.asc
book/07-git-tools/sections/advanced-merging.asc
book/07-git-tools/sections/replace.asc
book/07-git-tools/sections/reset.asc
book/07-git-tools/sections/searching.asc
book/07-git-tools/sections/submodules.asc

The book used a combination of Markdown and Asciidoc syntax for
bold and italic text. In the documentation, it says that * are
used for highlighting the whole word or phrase, and ** are used
to highlight a part of the word. The render still worked fine
before, but the source-code now follows the semantics.
http://asciidoctor.org/docs/user-manual/#bold-and-italic

Bold and italic follow Asciidoc semantics

---

book/05-distributed-git/sections/contributing.asc
book/07-git-tools/sections/bundling.asc

"git clone" does not say "Initialized empty Git repository" (it may have
done so in very old versions), but "cloning into '$repo'". Reflect this
in the examples.
Noticed by Tim Castelijns:
http://stackoverflow.com/questions/32580578/why-the-git-commit-am-command-is-working-with-untraked-file-in-the-documenta

Fix example output of "git clone"

---

book/01-introduction/sections/installing.asc

Compilation on Centos 6 requires perl-devel and docbook2X (uppercase X). I'm assuming this is the same for all other RHEL-likes.
docbook2X is only available through third-party repo like EPEL. Additionally, the binary is named `db2x_docbook2texi` instead of `docbook2x-texi` so symlinking is required.
Fixes #425.

Updated installing.asc for Centos/Fedora

---

book/01-introduction/sections/first-time-setup.asc

On a Windows system, even though you have setup Notepad++ as default
system editor, Git seems to behave oddly during operations and you may trip over
glitches, like prematurely terminated Git operations before your edits
are complete.
Setting up core.editor in Git explicitly to Notepad++ fixes this behavior.
Related:
- [Preview of changes](https://github.com/uNiversaI/progit2/blob/a9f0bb3dca1cc28c13058012f2a6a47c10adbb47/book/01-introduction/sections/first-time-setup.asc)
- [Discussion issue #365](https://github.com/progit/progit2/issues/365)

[core.editor] improve first time setup to include Notepad++

---

book/04-git-server/sections/smart-http.asc

Issues arise during the very basic setup of Smart HTTP using the tutorial.
1. User files generated with htdigest and htpasswd are not compatible.
Thus, if AuthType Basic is used, htdigest must be changed to htpasswd.
The fix also resolves #122.
2. Apache process doesn’t have write permissions for the /opt/git/ subdirectories.
To address this, I suggest restoring the paragraph from this section:
https://git-scm.com/book/en/v1/Git-on-the-Server-Public-Access.
Namely, `$ chgrp -R www-data /opt/git`.
3. Authentication fails during push.
The initial ref advertisement request will fail without even giving an opportunity for authentication.
This is described in the git-http-backend man page examples: https://www.kernel.org/pub/software/scm/git/docs/git-http-backend.html
I have updated and …

Improve Smart HTTP section

---

book/07-git-tools/sections/credentials.asc

I can't seem to find any information on using 'winstore' as a credential saving option on Windows. The link is outdated. 
With the default Git for Windows 2.6.1, when I run `git help -a` like the docs tell you to, it shows "crendential-wincred". 
https://git-scm.com/docs/gitcredentials
GitHub recommends to use "wincred" as well:
https://help.github.com/articles/caching-your-github-password-in-git/

change 'winstore' credential option to 'wincred'

---

book/A-git-in-other-environments/sections/zsh.asc

Patch for [#422](https://github.com/progit/progit2/issues/422#issue-108144184)
(As discussed in #422, this patch is made available under the MIT license.)

zsh += vcs_info and native completion

---

book/04-git-server/sections/git-daemon.asc

Had some issues following this text when setting up my own git server. [Upstart scripts in ubuntu goes in /etc/init/](http://upstart.ubuntu.com/cookbook/#job-configuration-file). 
Also the daemon should run with the --detached option or else the upstart job will not run in a daemonised manner.

upstart scripts go in /etc/init/

---

book/03-git-branching/sections/remote-branches.asc

When reading the paragraph about tracking remote branches, I found it weird that the simple `git checkout <branch>` command was not mentioned. For a quick refresh, here is what the man page says:
```
git checkout <branch>
[...]
If <branch> is not found but there does exist a tracking branch in exactly one remote
(call it <remote>) with a matching name, treat as equivalent to
$ git checkout -b <branch> --track <remote>/<branch>
```
I've almost never explicitly tracked a branch, I always use this syntax if I have 1 remote because it's short and obvious.
I'm open to suggestions/rewordings/criticism.

Mention shortest command to track remote branches

---

book/01-introduction/sections/installing.asc

On most linux distribution, the git package only provides the bare
command line git command. Just adding gitk and git-gui is the least.
I think that if we really wanted to provide the same level of features as the self packaged Git versions, we should even make people install the meta-package "git-all", that pulls git-svn, git-cvs, git-p4, gitweb and git-email.

[RFC] Add companions packages of git for linux installs

---

book/02-git-basics/sections/tagging.asc

Using single quotes results in the error - fatal: Failed to resolve '[tag name]'' as a valid ref.

Use quotes - Single quotes not platform independent

---

book/03-git-branching/sections/nutshell.asc

The rest of Section 3.1 describes pointers as pointing 'to' something, and on this particular line it was 'creates a new pointer at', which might make the sentence seem a little incoherent on first glance.

"pointer at" to "pointer to"

---

book/B-embedding-git/sections/libgit2.asc

There is unnecessary copyright mark at the beggining of "A2.2 Embedding Git in your Applications - Libgit2".
https://git-scm.com/book/en/v2/Embedding-Git-in-your-Applications-Libgit2
This is because of (((C))) in libgit2.asc is treated as a copyright mark.

fix a index for "C" in libgit2.asc

---

book/08-customizing-git/sections/attributes.asc

All modifications to the .gitattributes file are now illustrated using `[source,ini]` blocks. Previously it was a mishmash of `[source,ini]` and `[source,console] $echo foo >> .gitattributes` commands.

Update Ch8 to refer to .gitattributes consistently

---

book/07-git-tools/sections/stashing-cleaning.asc

The console output for these `git stash` examples didn't reflect reality.

Fix `git stash` examples

---

book/01-introduction/sections/first-time-setup.asc

Deleted a redundant sentence fragment rather than directly fix the typo.

Fix 'dependant' typo in first-time-setup.asc

---

book/09-git-and-other-scms/sections/import-svn.asc

git svn clones prefixes all SVN branch names by "origin/" in git, which is not wanted when migrating from svn to git. Hence, the prefix has to be stripped, simply in the same way it is done for tags already.

Strip "origin/" prefix from branch name

---

book/07-git-tools/sections/subtree-merges.asc

The superfluous "and vice versa" is incorrect here -- the two projects
/don't/ each have the other as subdirectories.  In fact only one has the
other as a subdirectory.
Fixes #486.

Remove superfluous phrase.

---

book/09-git-and-other-scms/sections/import-svn.asc

It is incorrect that git push origin -all would push tags on the git server. Actually you have to do git push --tags to also push the tags.

git push --all does not push tags

---

book/09-git-and-other-scms/sections/import-svn.asc

svn git creates 'trunk' branch which points to the same commit as 'master' which is simpy misleading. Let's just remove it!

Remove duplicate 'trunk' branch

---

book/09-git-and-other-scms/sections/import-svn.asc

It is not a fault that peg-revisions will result in multiple branches when migrating svn to git.

How to deal with peg-revisions

---

book/08-customizing-git/sections/policy.asc

Updated policy.asc in Chapter 8 to use a link to the relevant section in Chapter 7 rather than a hardcoded and incorrect reference to Chapter 6.

Replace hardcoded incorrect reference to Chapter 6

---

book/03-git-branching/sections/nutshell.asc

Make commit messages consistent with the preceding figure and correct the `(HEAD -> master, testing)` `--decorate` output.

Make output of `git log` consistent with preceding figure

---

book/02-git-basics/sections/recording-changes.asc
book/07-git-tools/sections/rewriting-history.asc
book/09-git-and-other-scms/sections/import-svn.asc
book/10-git-internals/sections/objects.asc

Most of the time, file names are marked up like so: `filename.txt` -- in a few places there is no markup and in others it's done in this way: ``filename.txt''. This commit makes them all consistent.

Make examples that refer to files by name consistent

---

book/02-git-basics/sections/viewing-history.asc

In section 2.3 Git Basics - Viewing the Commit History, the final example is: `git log --pretty="%h - %s" --author=gitster --since="2008-10-01" \
--before="2008-11-01" --no-merges`. The explanation says
> and were not merged in the month of October 2008
If I understand correctly the documentation in
>--no-merges
Do not print commits with more than one parent. This is exactly the same as --max-parents=1.
this means that the merge commits themselves will be excluded. So if a commit occured in Oct, but merged in Nov it will still be shown in the output.

More accurate explanation for git log example

---

book/07-git-tools/sections/subtree-merges.asc

Most people won't want to intermingle the subtree project's tags with their own.

avoid fetching subtree's tags into project's tagspace

---

book/05-distributed-git/sections/maintaining.asc

Do we really need to use the full e43a6fd3e94888d76779ad79fb568ed180e5fcdf value in git cherry-pick e43a6fd3e94888d76779ad79fb568ed180e5fcdf . Couldn't it be git cherry-pick e43a6 ?

Full sha1 value

---

book/03-git-branching/sections/remote-branches.asc

A tracking branch is not an upstream of something.
Back in pre-git-v1.7 era “tracking branch” also meant remote-tracking branch, and that kind of tracking branch was often an upstream of a local branch.
Today the terminology has been clarified, so a “tracking branch” usually is (at least in the rest of this section) a local branch that tracks an upstream branch.

Fix explanation of upstream branch

---

book/04-git-server/sections/git-daemon.asc

--detach will fork and trigger an endless loop of respawns
If --detach is used you probably want to specify
expect fork[1]
[1] http://upstart.ubuntu.com/cookbook/#expect-fork

Remove --detach from local-git-daemon.conf

---

book/08-customizing-git/sections/config.asc
book/09-git-and-other-scms/sections/import-tfs.asc
book/10-git-internals/sections/objects.asc
book/10-git-internals/sections/packfiles.asc

I've put several small fixes to one PR, I hope this will save your time.
If it's better to make separate PRs for them - please tell me.

Small fixes

---

book/02-git-basics/sections/remotes.asc

There is no `git add remote`, related command, or statement in previous sections, but `git clone`.
And the only remote repository mentioned is "origin" which is added automatically via clone command.
Fix the sentence for that.
Only one question: the words `directly` vs. `explicitly`. **Which one is better?**

Fix issue #526: There is no *adding* remote repositories in previous sections.

---

book/02-git-basics/sections/remotes.asc

Also fix "remote branch" to "remote-tracking branch".

Fix issue #534: `git remote rename` does not rename *a* reference

---

book/07-git-tools/git-credential-read-only

Hello,
In the current version, the first entry matching protocol/hostname and not protocol/username/hostname is returned.
For exemple:
.git-credentials:
```
http://titi:pwd1@exemple.com (1)
http://toto:pwd2@exemple.com (2)
```
then
```git clone http://toto@exemple.com``` will match (1) instead of (2).

git-credential-read-only should match against username

---

book/07-git-tools/sections/credentials.asc

I tried the following example from the book and it just displayed the help for `git config`:
```
git config --global credential.helper store --file ~/.my-credentials
```
After a bit of research I found the [git-credential-store(1) Manual Page](https://git-scm.com/docs/git-credential-store/1.7.12.1) which actually puts single quotes around the `store --file ~/.my-credentials`, which worked for me. I'm using git version 1.9.1, not sure if that makes a difference.
Note that there's another example at the bottom of this page, `git config --global credential.helper read-only --file /mnt/shared/creds`, which might also require single quotes around its last part to work, but I'm not sure, so I didn't change that.

Fix cmdline in credentials.asc

---

book/02-git-basics/sections/recording-changes.asc
book/08-customizing-git/sections/config.asc

it really is a filename that ends with a `~`, instead of a file that ends with a `~`

fixed to be more precise

---

book/09-git-and-other-scms/sections/import-svn.asc

#550 Add note that it is not recommended to use --no-metadata because it may breaks
synchronisation between git and svn.

Add recommendation note

---

book/02-git-basics/sections/recording-changes.asc

Fixes #554 and delete duplicate space.

Fix issue #554: The output of 'git status' is out-of-date

---

book/01-introduction/sections/first-time-setup.asc

Fixes #384 
Use "version 2.x of Git for Windows"

Fix issue #384: There's no Git for Windows 2.x

---

book/02-git-basics/sections/recording-changes.asc

Fix issue #577: One command is `git mv`, instead of `mv`.

---

book/03-git-branching/sections/nutshell.asc

A first time reader sees "Staging the files checksums" and immediately wonders whether there's a typographic or grammatical error. While "checksum" sometimes occurs as a verb (see Wordnik, below), it is more often considered a noun (see Oxford and Webster, below).
A little editing removes the checksum ambiguity for more readers.
Oxford. http://www.oxforddictionaries.com/definition/english/checksum
Webster. http://www.merriam-webster.com/dictionary/checksum
Wordnik. https://www.wordnik.com/words/checksum

Branches in a Nutshell: Use unambiguous checksums

---

book/05-distributed-git/sections/contributing.asc

Directly above this example commit message it's stated that one should use the imperative present tense, so I think it's best to show that right away in the following example.
Note that I'm redoing this PR, since my last one (#222) was so long ago I thought this would be easier than updating/merging/rebasing.

Change message to use imperative present tense

---

book/09-git-and-other-scms/sections/import-svn.asc

In order to get a list of authors from a Subversion repository,
we extract the authors from the output of `svn log --xml`. We
then try to filter out the author field by grepping for 'author'.
This produces incorrect results in the case where a commit's
message contains the word 'author'.
Fix the issue by invoking `svn log --xml --quiet` instead, which
suppresses the commit's message.

Harden retrieval of author list from Subversion

---

book/03-git-branching/sections/remote-branches.asc

In the PDF, page 113, a linebreak is automatically inserted after the dashes within the option “--all”, which makes ambiguous whether a space should be inserted or not.
(I made two commits because I made a mistake in the first commit and I’m not yet at ease with git, but the two commits are meant as a single one.)

linebreak deletion

---

book/09-git-and-other-scms/sections/import-svn.asc

The on-disk image of a git repository has changed in recent versions of w.r.t to how svn-git stores remote branches and tags. As a consequence the bash commands told in this section of the book did not work anymore. My proposal solves this issue. I tested it today against 2.1.4, so I assume the change happened with v2.0 or v2.1 and should work with newer Git versions, too.

Adapted to current git version

---

book/09-git-and-other-scms/sections/import-svn.asc

Typically one wants to keep all peg-revisions or none, so I want to propose to give the exact code line for removing all peg-revisions at once.

Removing all peg revisions by one command

---

book/07-git-tools/sections/submodules.asc

I was looking into submodules and subtrees recently, and one of the reasons I decided to go with submodules was because there was a config option that forced safer behavior for pushing submodule changes.
I figured it'd be nice if the section mentioned the config; hopefully this will help someone else consider using submodules if they can enforce a team wide use of the config.

Reference the 'push.recurseSubmodules' config in the section on pushing submodule changes

---

book/09-git-and-other-scms/sections/client-svn.asc

Remove references to the nonexistent progit-example.googlecode.com domain. I can't see standing up that example repo given the limited value of the exercise.
Fixes #631

Remove references to deleted googlecode.com domain

---

book/A-git-in-other-environments/sections/powershell.asc

I installed some of the latest GitHub for Windows versions on Windows 10 and no PoSh-Git gets installed, so i think this information deprecated.

Removed Posh-Git GitHub for Windows reference

---

book/08-customizing-git/sections/config.asc

Escaping the quotes causes errors. Double quotes should not be escaped because the command is surrounded by single quotes.

Remove quote escape.

---

book/02-git-basics/sections/undoing.asc

The note is confusing as the example before it does not use `git reset --hard`. This was mentioned in closed issue #547.

Update git reset --hard note for clarity

---

book/08-customizing-git/sections/attributes.asc

Paths and filenames containing spaces would not be diffed without the
quotes

8.2: Surround docx path with quotes

---

book/02-git-basics/sections/remotes.asc

Most of the `git remote` command names are verbs e.g add, show, rename etc. It's a good idea to add `git remote remove` as the first one. Easy to remember with other commands (add/remove). Hence I also updated the example.

Add git remote remove command

---

book/08-customizing-git/sections/attributes.asc

It is necessary to escape quotation marks in the git message, otherwise it ends the commit's message.

added escaped quotation marks for git commit's message.

---

book/08-customizing-git/sections/config.asc

The switch `trailing-space` was used without mentioning what it means, and I think the command didn't set `tab-in-indent`.
Besides, after some trying, I find that "leaving them out of the setting string" doesn't disable the settings, but will only keep the default value unchanged. For example, if I want all but `cr-at-eol` to be set, I can simply do: `git config --global core.whitespace indent-with-non-tab,tab-in-indent`.
Maybe we can confirm the behavior and add more clarification for this part.

Clarify explanation of configuring core.whitespace

---

book/10-git-internals/sections/objects.asc

Restores missing step: update cache to point to "new" test.txt (`1f7a7a472abf3dd9643fd615f6da379c4acb3e3a`) when building the tree `0155eb4229851634a0f03eb265b69f5a2d56f341`
When building the tree whose SHA1 will be `0155eb4`, the text says _"You’ll now create a new tree with the second version of test.txt and a new file as well"_, but it never updates the index to point to the second version of test.txt, which means that when you run `git write-tree` in the next step you don't get `0155eb4229851634a0f03eb265b69f5a2d56f341` as the SHA.
This patch adds a step to the instructions that updates the index to point to that second version of test.txt. When you include this step, you get the right SHA.
(Fixes #608)

(Book) Restores missing step in objects.asc

---

book/08-customizing-git/sections/config.asc

Well, this is actually a followup of https://github.com/progit/progit2/pull/698 .
As mentioned in that PR, I found that "leaving them out of the setting string" doesn't disable the settings, but will only keep the default value unchanged. Commits in this PR try to reflect that.

Correct wrong statement on whitespace config

---

book/05-distributed-git/sections/contributing.asc
book/05-distributed-git/sections/distributed-workflows.asc
book/05-distributed-git/sections/maintaining.asc

I have made a few changes that I thought would improve the text. It probably might not :). Few other improvement I thought would make the book better are listed below. Please provide suggestions. 
- There is a line specifying a person named _Tim Pope_ in the _Commit Guidelines_ subsection of the _Contributing to a Project_ section. It would be more clear, if a line about the person was added there.
-  In the commit template found in the _Commit Guidelines_ subsection of the _Contributing to a Project_ section, there's a line that reads like this, 
> The blank line separating the summary from the body is critical (unless you omit the body entirely); tools like rebase can get confused if you run the two together.
It would be better if the reason, why tools like rebase get confused was …

Few changes to the "Distributed Workflow" chapter

---

book/03-git-branching/sections/basic-branching-and-merging.asc

A picture in chapter 3 had a branch name that was not previously monospaced. This commit monospaces that word to maintain consistency with other parts of the book

Monospaced a word in picture's caption to fix #598

---

README.asc

The build is no longer performed by Atlas. We are on our own for publishing.
@ben do we need more on this?

Remove references to Atlas.

---

book/06-github/1-github.asc
book/06-github/sections/2-contributing.asc
book/06-github/sections/3-maintaining.asc
book/06-github/sections/5-scripting.asc

A few suggestions are required for the following change,
- In the last code sample found in the _Commenting on an Issue_ subsection of the _Scripting GitHub_ section (just above figure 6-54) has a line like this,
```
$ curl -H "Content-Type: application/json" \
-H "Authorization: token TOKEN" \
....
```
The second line seems to need a token generated using GItHub in place of which the word TOKEN is placed. Wouldn't it be nice to add a note about that in that section?

Added a few changes to the "GitHub" chapter

---

book/10-git-internals/sections/objects.asc

The orphan blob d670460b4b4aece5915caf5c68d12f560a9fe3e4 is not in the
figure. So the figure is not of "All the objects" but rather all the
reachable ones.
Fixes #725.

Fix figure title

---

book/06-github/sections/2-contributing.asc

in Chapt. 6 Sect. 2, the following command seems to have a typo, causing the error below: 
>$ sed -i '' 's/1000/3000/'  blink.ino
>sed: can't read s/1000/3000/: No such file or directory

2-contributing.asc: sed command fix/type

---

book/04-git-server/sections/smart-http.asc

Use `Require expr` feature of `mod_authz_core` to remove the need for mod_rewrite and simplify the entire configuration. 
This is my idea to fix issue #730. The single `Require expr ...` line replaces all of the rewrite rules and the Order/Deny/Satisfy lines.
Someone who knows more about Git than I do should probably verify that this configuration does what is needed. It seems to work for me, but I am much more knowledgeable about Apache configuration than Git's inner workings, so my testing of it may not have covered all cases.

Update and simplify Apache config

---

book/07-git-tools/sections/credentials.asc

Wincred is no longer maintained and has been replaced by Git Credential
Manager for Windows.

Update outdated information for credential storage.

---

book/09-git-and-other-scms/sections/import-bzr.asc

There was an error about the package to install with RHEL to import a Bazaar repository into a Git repository.
The good one is `bzr-fastimport`.

bzr-fastimport

---

book/06-github/sections/2-contributing.asc

A list was badly formed and that produced a WARNING at the generation of the book.
It is necessary to put the item <3> at the end of the line to generate correctly the book.

Generating the book

---

book/01-introduction/sections/first-time-setup.asc

- Text referred to "either" editor when several were listed
- Make the "Warning" less vague/confusing (I interpret it as being about what could happen if Git can't find an editor)

Minor text changes to First-time Git setup

---

book/04-git-server/sections/gitlab.asc

Hello,
I realized that there are some problems with the PDF version of progit in the section GitLab due to the xml entity representing the right arrow.
The problems were :
* the link to bitnami was not correctly formed
* in the french version, the apostrophe was replaced by "&amp;#8217;"
* the right-arrow doesn't appear as it should be.
Here are the changes I made :
* replaced the '-' delimiter by a '+'
* replaced the xml entity that represents the right arrow by the symbol of the right arrow ('→')
Adrien Ollier

corrected the representation of the combination of keys "alt + →"

---

book/09-git-and-other-scms/sections/client-svn.asc

The original SVN test repository is gone.
The reader have to use another SVN test repository.
Related to #631 and #653.

SVN test repository

---

README.asc

added instructions to build the book

---

book/07-git-tools/sections/revision-selection.asc
book/07-git-tools/sections/rewriting-history.asc
book/07-git-tools/sections/searching.asc
book/07-git-tools/sections/signing.asc
book/07-git-tools/sections/stashing-cleaning.asc

This PR adds a few changes to chapter 7 of the book that seemed good to me ;) Few more changes are to would possibly be made in a following PR. There's one change that I wanted to make in this PR but held it back to get comments regarding it. It's regarding the lines quoted below found in the _Changing the Last Commit_ subsection of the _Rewriting History_ section,
> You stage the changes you want by editing a file and running `git add` on it or `git rm` to a tracked file, and the subsequent git commit --amend takes your current staging area and makes it the snapshot for the new commit.
As far as I know, amending takes things in the current staging area and *adds* it to the snapshot of the last commit. So shouldn't the above sentence be rephrased as follows,
> You stage the changes you …

Changes for chapter 7

---

book/02-git-basics/sections/recording-changes.asc

Improve comment about what the '**' glob pattern does.

Improve comment about what the '**' glob pattern does.

---

book/04-git-server/sections/gitweb.asc

In apache2.4 mixing `Options` with a `+` or a `-` with those without
will cause startup to abort. This patch updates the example gitweb
apache virtualserver to a valid configuration for apache2.4.

Update gitweb apache example for apache2.4

---

book/02-git-basics/sections/recording-changes.asc

While reading this excellent book on Git,  in section 2.2 (Recording Changes...), found a slightly confusing use of the term "index" in the section on removal of files:
"The next time you commit, the file will be gone and no longer tracked. If you modified the file and added it to the index already ..."
I don't believe "index" was discussed in the prior sections, so  I replaced "index" with "staging area" which I think is what index is referring to.  This seems to read a little more consistently or clearly relative to the rest of the material.  I hope this is helpful.  Thanks.

replaced "index" with "staging area" in section 2.2

---

book/01-introduction/sections/first-time-setup.asc

This aims to address the confusion that leads to pull requests like #733, #732, #707, #671, and probably others. It aims to be more explicit with the`core.editor` instructions when it comes to 32-bit editors on a 64-bit system.

Resolve 32/64-bit confusion for Windows editors

---

book/10-git-internals/sections/environment.asc

The documentation for GIT_WORK_TREE incorrectly states that it will default to the parent directory of GIT_DIR. This contradicts the actual behavior and documentation of `core.worktree` in git-config(1): https://git-scm.com/docs/git-config#git-config-coreworktree
Do you think the same warning should be included in the documentation for `GIT_DIR`? I found this to be kind of a footgun when using `GIT_DIR`.

Correct documentation for GIT_WORK_TREE based on git-config(1)

---

book/02-git-basics/sections/tagging.asc

This commit updates the section on checking out tags by replacing
the old text saying you can't really do it with a short paragraph
explaining how to do it.
---
Just a small tweak I found when reading up on tagging today. This removes the explanatory text after the command example too, which has not been replaced (partially because I wasn't sure exactly what to put there, and partially because it no longer seems as relevant, as it works the same way as when checking out commits), though I would be happy to do so if it is deemed necessary.
Fixes #784.

Correct section on checking out tags

---

book/B-embedding-git/sections/jgit.asc

Unfortunately there is no generic javadoc link anymore.
I linked the latest stable version.
Old version docs are not removed so this should keep working.
The previous link leads to a project page and there is no link to the javadoc on that page.

fix jgit javadoc link

---

book/06-github/sections/2-contributing.asc

The caption of Figure 100 and Figure 101 is the same. I changed the 101 to "Link back to the new Pull Request in the closed Pull Request timeline" that I think is more related to the context.

Change figure 101 caption

---

book/02-git-basics/sections/getting-a-repository.asc
book/02-git-basics/sections/recording-changes.asc
book/02-git-basics/sections/remotes.asc
book/02-git-basics/sections/tagging.asc
book/02-git-basics/sections/undoing.asc
book/02-git-basics/sections/viewing-history.asc

- adjust some filenames/commands to use monospaced font
- standardize on <> for replaceables, [] for optionals
- Remove '$' in front of shell variables when only discussing them
- Add "--oneline" option to log option table, given its popularity
- Add NOTE clarifying "--all-match" option to git log
- Minor rewording in a couple places for clarity

Various grammar/font/clarification fixes to Chapter 2.

---

book/07-git-tools/sections/reset.asc

git checkout can be used to reset a file in the work tree to the current HEAD without specifying any further, so the commit parameter is optional.

Use square brackets for checkout [commit] [file]

---

book/02-git-basics/sections/recording-changes.asc

Warn the reader briefly about the possibility of multiple .gitignore files
in a single repository, and refer them to "man gitignore" for more details.

Add a short note mentioning there could be multiple .gitignore files.

---

book/07-git-tools/sections/debugging.asc

- italics for emphasis
- change [commit] to <commit> since first invocation requires commit

A couple minor tweaks to Ch 7, "Debugging with Git" section.

---

book/07-git-tools/sections/rewriting-history.asc

Changes include:
- Adding NOTE to emphasize rewriting history should be local.
- Add recursive option to example about removing editor backup files.

Minor grammar/clarification tweaks to Chapter 7, "Rewriting History"

---

book/08-customizing-git/sections/config.asc

Throw in a bit more detail into the sample commit template file.

Expand on the rationale for creating a custom commit template.

---

book/02-git-basics/sections/getting-a-repository.asc

Self-explanatory -- given that you haven't initialized the project
directory as a Git repo yet, it shouldn't be called a "repository".

Rename project directory to emphasize that it's not a Git repo yet

---

book/04-git-server/sections/git-daemon.asc

systemd being the most common init system on Linux distributions, it seems logical to mention it.

Update to add systemd daemon exemple

---

book/02-git-basics/sections/remotes.asc
book/02-git-basics/sections/tagging.asc
book/03-git-branching/sections/remote-branches.asc
book/07-git-tools/sections/stashing-cleaning.asc
book/09-git-and-other-scms/sections/client-svn.asc
book/10-git-internals/sections/refs.asc

I'm a big believer in consistency.

Standardize on <remote>, not <remotename> or <remote-name> for examples

---

book/05-distributed-git/sections/contributing.asc
book/10-git-internals/sections/objects.asc

As I was reading section 10.2 regarding git internals and tree creation, I found what I think might be a minor omission of an "--add" flag and a superfluous "update-index" statement.  I provide what I believe is a more streamlined and corrected version in this PR.  Thanks.

Minor cleanup in 10.2 regarding new tree creation and in 5.2 to explain format of return message from push.

---

book/01-introduction/sections/first-time-setup.asc

While it might seem obvious, it doesn't hurt to state explicitly that changing
/etc/gitconfig is restricted to privileged users.

Emphasize changing /etc/gitconfig requires admin/superuser privilege.

---

book/01-introduction/sections/help.asc

Be clearer about the distinction between the manpages for a Git command,
and the much more terse "-h|--help" option.

Expand the "Getting Help" section to explain manpages versus "-h".

---

book/02-git-basics/sections/recording-changes.asc

No major changes, just some rewording, clarification, font changes where I thought
it was useful.

Wording/grammar/clarification tweaks to "Recording Changes" section

---

book/02-git-basics/sections/viewing-history.asc

Given how merge commits can clutter up one's log output,
make sure readers understand the --no-merges option.

Add a TIP explaining the log option '--no-merges'

---

book/02-git-basics/sections/tagging.asc

- Clarify the need for [-l|--llist]
- Some minor rewording

Add TIP to tagging section explaining "-l"; also some rewording

---

book/04-git-server/sections/git-on-a-server.asc
book/04-git-server/sections/protocols.asc

The original asciidoc link name displayed to the reader was
"Git on the Server", which is in fact the very name of the
chapter, which is somewhat confusing, so change the link name
to reflect the actual section name.

Rename "Getting Git on a Server" link to reflect the section name

---

book/02-git-basics/sections/getting-a-repository.asc
book/02-git-basics/sections/remotes.asc
book/C-git-commands/1-git-commands.asc

At commit 3ba700370, @rpjday forgot to update all the references to "_git_on_the_server" when he changed it to "_getting_git_on_a_server".
This update fixes that.

updated all the references to "_git_on_the_server"

---

book/05-distributed-git/sections/maintaining.asc

Changes include (among other things):
- standardize on " -- " for em dashes
- rewording for clarity
- make sure the word "git" is included in sample Git commands
The rationale for that last change is that this is the first chapter
that referred extensively to both the Unix "diff" command and the
Git "git diff" command, so I decided to make sure that Git command
examples explicitly started with the word "git", to avoid ambiguity.

Numerous tweaks (rewording/grammar/fonts) to "Maintaining a Project"

---

book/09-git-and-other-scms/1-git-and-other-scms.asc
book/09-git-and-other-scms/sections/client-svn.asc

I made varied corrections:
- moved a comma at its right place
- replaced "working repository" by "working directory"
- reworded the sentence about fetching the commits from the SVN repository and commiting them in the local Git repository
- emphasised "dcommit"

Git client SVN

---

book/04-git-server/sections/git-daemon.asc
book/07-git-tools/sections/debugging.asc
book/07-git-tools/sections/stashing-cleaning.asc

@buzut and @rpjday made some changes and introduced inadvertently space trailing:
```console
$ git blame -L 49,55 master -- book/04-git-server/sections/git-daemon.asc
26c829ee (Buzut            2017-10-07 21:12:57 +0200 49) You might have noticed that Git daemon is started here with `git` as both group and user. 
26c829ee (Buzut            2017-10-07 21:12:57 +0200 50) 
26c829ee (Buzut            2017-10-07 21:12:57 +0200 51) Modify it to fit your needs and make sure provided user exists on the system.
3c5c45a3 (Buzut            2017-10-05 21:28:09 +0200 52) 
e78ad789 (Robert P. J. Day 2017-10-21 11:47:15 -0400 53) Finally, you'll run `systemctl enable git-daemon` to automatically start the service on boot, and can start and stop the service with, respectively, `systemctl start …
```

removed trailing spaces

---

book/07-git-tools/sections/interactive-staging.asc

Cleaning includes:
- standardize using " -- " for em dash
- Rewording for clarity
- Add "git" command prefix to sample Git commands

Standard cleanup of "Interactive Staging" section

---

book/07-git-tools/sections/stashing-cleaning.asc

Standard cleanup and including:
- standardize on " -- " for em dashes
- rewording for clarity
- add TIP about save being deprecated in favour of push

Basic cleanup of stash part of "Stashing and Cleaning" section

---

book/10-git-internals/sections/plumbing-porcelain.asc

I changed the words "verbs" to "subcommands" since many Git commands
don't qualify as verbs -- things like "remote" and "log" and "status".

Minor tweaks/grammar/clarification fixes for "Plumbing and Porcelain"

---

book/10-git-internals/sections/objects.asc

'it' replaced by 'is' in chapter 10, section 'objects', line 8th, word 4th

'it' replaced by 'is' in 10th chap, objects section

---

book/02-git-basics/sections/recording-changes.asc

The sentence "If you've staged all of your changes, `git diff` will give you no output." sounds nice by itself, and treats the behavior as a feature to be expected rather than a complication.

Remove "this can be confusing, because"

---

book/04-git-server/sections/git-daemon.asc

systemd config file uses full path to git binary.

---

book/02-git-basics/sections/recording-changes.asc

Previous wording ("Changed but not updated") didn't match what git outputs ("Changes not staged for commit").

Wording correction under "Removing Files" section

---

book/07-git-tools/sections/reset.asc

Guessing this should be from/to, as that's what a "trivial merge" would probably do:
so all of the files you _haven't_ changed in will be updated.   <=was
so all of the files you _haven't_ changed will be updated.       <=suggesting as simpler than the other option:
so all of the files you _haven't_ changed in it will be updated. <= possible alternative

fixed minor grammar mistake

---

book/01-introduction/sections/installing.asc

Was working with a person new to git and they were confused about how to run git from the terminal as suggested in the installation process for mac

indicate what running git from the terminal actually is for a newbie

---

book/09-git-and-other-scms/sections/client-bzr.asc
book/09-git-and-other-scms/sections/import-bzr.asc

Bazaar has a more extended syntax than Git to ignore some files.
Then it is necessary to adapt the exclusion file of the Git repository
to take into account the possible incompatibilities.

taking into account the syntax of Bazaar

---

book/A-git-in-other-environments/sections/powershell.asc

Added a section about the PowerShell Gallery and how to pull and update PowerShell Modules from there.
Add Update PowerShell Prompt section.

Mention PowerShell Repository

---

book/03-git-branching/sections/remote-branches.asc

Clarifying "merge in" vs "merge into".

Update remote-branches.asc: Resolves #963

---

B-embedding-git-in-your-applications.asc
book/B-embedding-git/sections/go-git.asc

Adds one more way of embedding Git in your application using  [go-git](https://github.com/src-d/go-git) project.
go-git is quite mature, well maintained and used in production by a multiple companies implementation of Git in Golang.
Please, let me know if you guys think it could be of any value for the readers.

Add go-git to Appendinx B: embedding

---

book/10-git-internals/sections/objects.asc

usage of `git cat-file -p master^{tree} command` in other environments as specified in this answer https://stackoverflow.com/a/17121954/2445295 thanks to @Mellbourn

git cat-file -p master^{tree} in other shells

---

book/09-git-and-other-scms/sections/import-hg.asc

As maintainer of hg-fast-export I have received at least one issue (frej/fast-export#116) due to the example in Ch9 no longer working with a recent hg-fast-export. In order to avoid future user confusion I propose the changes in this pull request.

Update Ch9 section about Mercurial imports to match current hg-fast-export release

---

book/09-git-and-other-scms/sections/import-bzr.asc

Bzr would not find plugin in the old place on Ubuntu 16.04.

Fix bzr fastimport plugin install guide

---

book/06-github/sections/1-setting-up-account.asc
book/06-github/sections/2-contributing.asc

In two instances, a comma was used when other punctuation would have
been more appropriate to seperate the two independant caluses.

Fix comma splices

---

book/02-git-basics/sections/getting-a-repository.asc
ch02-git-basics-chapter.asc

- use proper "em" dash
- adjust wording to explain clone target directory name

"Git Basics" chapter: tweak a couple things for aesthetics/clarity

---

book/01-introduction/sections/about-version-control.asc
book/01-introduction/sections/command-line.asc
book/01-introduction/sections/first-time-setup.asc
book/introduction.asc

Stylistic/aesthetic adjustments, including:
- use "--" for em-style dashes, not special characters
- remove superfluous Oxford comma
- add some commas where they're warranted
- expand on the "git config" options

Make some stylistic tweaks to Chapter 1, Introduction

---

book/03-git-branching/sections/nutshell.asc

nutshell.asc: minor tweaks for fonts/wording/emphasis

---

Rakefile

Users should get version number from git rather than a
possibly non-existent environment variable.

Get Version from git describe not travis envvar

---

book/07-git-tools/sections/searching.asc

searching.asc: mention that "git grep" can search the index as well

---

book/10-git-internals/sections/objects.asc

Add hash-object to validate ruby hash function

---

B-embedding-git-in-your-applications.asc
book/B-embedding-git/sections/dulwich.asc

Adds one more way of embedding Git in your application using  https://www.dulwich.io project.
Dulwich is independent Python implementation of the Git file formats and protocols.
As it touches the same files, it's based on/includes a commit from #998 and so will be rebased on top of it. Only ee2d9dd needs to be reviewed in here.

Add Dulwich to Appendinx B: embedding

---

book/10-git-internals/sections/objects.asc

> "A single tree object contains one or more tree entries"
The language suggests that each tree object contains (at least one) reference to another tree object, which is wrong.

Tree objects don't nec. point to trees

---

book/B-embedding-git/sections/dulwich.asc
book/B-embedding-git/sections/go-git.asc
book/B-embedding-git/sections/jgit.asc

Following up on discussion at https://github.com/progit/progit2/pull/999#discussion_r198919430.
Remove unnecessary quotes from index entries in Embedding section.

Remove quotes from index entries

---

book/07-git-tools/sections/revision-selection.asc

Fixing a typo where you wrote HEAD^^^ instead of HEAD~~~ (occurs in two places).

HEAD~3 is equivalent to HEAD~~~, not HEAD^^^

---

book/04-git-server/sections/generating-ssh-key.asc

I know the documentation here suggests you don't need a password, but I am suggesting this change for two reasons:
1) If the user does want a password, they will want to use the -o option. Not using the -o option makes the password practically worthless. See here for details: https://latacora.singles/2018/08/03/the-default-openssh.html
2) This documentation comes up on the top 10 Google search results for "how do I make an ssh key". It's likely that ssh users (even experienced ones) may use this guide to create new keys. It is important to get users into the habit of using the -o option, since it should be the default for the command anyway, but for whatever reason was never updated as such.

Update ssh-keygen with secure password encryption

---

book/04-git-server/sections/generating-ssh-key.asc

Add brief explanation of
ssh-keygen -o
option.

Explain -o option in ssh-keygen

---

book/02-git-basics/sections/viewing-history.asc

In the section 2.3, if one wants to see the changes made by the author
Junio Hamano, the author name cannot be gitster. Fixed the same.

Fixed the author name

---

book/02-git-basics/sections/recording-changes.asc

whether the file is modified or has been added to the staging area, the -f option is needed to force the removal

change the describe of when should force the removal with the -f option

---

book/A-git-in-other-environments/sections/powershell.asc

I updated links and also added new lines to improve readability.

PowerShell links update

---

book/01-introduction/sections/installing.asc

At the end of the next sub-chapter of the tutorial (Getting-Started-First-Time-Git-Setup) we are presented with code example:
`$ git config --show-origin rerere.autoUpdate
file:/home/johndoe/.gitconfig	false`
but that function was implemented in 2.8.0 and doesn't work with git 2.0.0.
I've installed git from Ubuntu repos, git ver 2.7.0, and was surprised that something didn't work, even though version used was far more up to date than 2.0.0. 
An alternative would be to add a warning for the reader in  Getting-Started-First-Time-Git-Setup, that `git config --show-origin` works only in 2.8.0 and later.

Change suggested Git version from 2.0.0 to 2.8.0

---

book/01-introduction/sections/basics.asc

Among other things:
- remove unnecessary hyphenation
- font changes for emphasis

chapter 1: minor grammatical/font changes for consistency

---

book/02-git-basics/sections/recording-changes.asc
book/02-git-basics/sections/viewing-history.asc

chapter 2: minor clarification and punctuation fix

---

progit.asc

f2678ab introduced the management of version strings by command line
attributes, but left an empty line after the authors. This seems to
upset Asciidoctor which finds an error elsewhere.
Removing the empty line seems to make it back happy.
fix #1134

Remove the empty version line

---

book/05-distributed-git/sections/maintaining.asc

chapter 5: minor rewording for clarity

---

book/07-git-tools/sections/interactive-staging.asc

The newer form of interactive staging uses square brackets
to emphasize single-letter shortcuts.

interactive staging: update prompts to include "[]" for shortcuts

---

book/05-distributed-git/sections/maintaining.asc

Once upon a time, "git describe" worked only with annotated tags;
these days, using "--tags" option allows use of lightweight tags.

maintaining: explain how "git describe" works with lightweight tags

---

book/07-git-tools/sections/stashing-cleaning.asc

A number of minor changes to stashing section, including:
- emphasize "push" instead of "save"
- introduce "--all" to include ignored files

stashing/cleaning: clean up some wording, mention "--all" for stashing

---

book/03-git-branching/sections/rebasing.asc

This pull requests wants to fix #1152 regarding when a user should and should not be doing rebase.
I have form it in a way trying to minimize the additions in the book.
Another option would be to add some section about how git and rebase can play a role in continous integration systems.
I am not native english, it would be great if some native english could review it.

Clarify when is not recommended to rebase

---

book/04-git-server/sections/protocols.asc
book/04-git-server/sections/smart-http.asc
book/06-github/sections/2-contributing.asc
book/07-git-tools/sections/debugging.asc
book/07-git-tools/sections/interactive-staging.asc
book/07-git-tools/sections/revision-selection.asc
book/07-git-tools/sections/rewriting-history.asc
book/07-git-tools/sections/signing.asc
book/07-git-tools/sections/stashing-cleaning.asc
book/07-git-tools/sections/submodules.asc
book/07-git-tools/sections/subtree-merges.asc
book/09-git-and-other-scms/sections/import-bzr.asc
book/10-git-internals/sections/refs.asc
book/introduction.asc
ch07-git-tools.asc

Found the use of this single quote ’ instead of ' (which looks slightly different).
I found them on files with extension:
- `.sketch` *
- `.pdf` *
- `.png` *
- `.ico` *
- `.asc` (15 files)
_* I didn't modify these since they are binary files which happen to contain them in their gibberishy binariness._
Then also noticed double single-quotation was being used (perhaps for some templating or idk), but I was careful not to mess with them (used a negative lookbehind regexp: `(?<!’)’` )

single-quote normalization

---

book/10-git-internals/sections/refspec.asc

The document mentioned that the default behavior of the command `git remote add`  lead to writing the changes locally in `refs/remotes/origin/`. It will be good to make the example command more specific by mentioning `origin` to match the command example with the command result.

Small edit to 10.5 Git Internals - The Refspec

---

book/04-git-server/sections/git-on-a-server.asc

Added a line about running `git init` even after cloning the repo, as it can be unclear that this command is non-destructive.

Added clarification about repo re-initialization

---

book/07-git-tools/sections/advanced-merging.asc

This suggestion aligns the formatting with the next paragraph. Checked for other occurrences of ``` `--\w+' ``` but found none.

Format quoted option string as <code> in HTML

---

book/08-customizing-git/sections/hooks.asc

- Fixed a typo in hooks.asc.  Issue #1169.

---

book/01-introduction/sections/help.asc

The irc.freenode.net url is repetedly reported to host botnet control - C&C software so it should be removed.
Many(or most) new commers to git are not familiar with IRC so pointing them to freenode's main page might be more helpful since it has some basic info on IRC and a link to the chat url (https://webchat.freenode.net/)
Fixes #1154.

point to the freenode main page

---

book/04-git-server/sections/setting-up-server.asc

- vim should not be run as root, but instead use `sudo -e`
(or sudoedit) which creates a temporary copy of the file
to edit and then copies it over the original if you modify the
contents.

Fix usage of sudo to edit file

---

book/01-introduction/sections/what-is-git.asc
ch01-getting-started.asc

Rename 'Git Basics' from chapter 1 to 'What is Git?'

---

book/02-git-basics/sections/recording-changes.asc

Recording changes: Replace lone, single hyphen with proper "--"

---

book/02-git-basics/sections/undoing.asc

The current explanation of "git checkout -- <file>" seems a bit
vague, so expand on it ever so slightly.

Undoing things: Clarify what "git checkout" does to local files

---

book/02-git-basics/sections/tagging.asc

Among other things:
- explain that pushing tags pushes both types
- add second variation of how to delete remote tags

Tagging: Small amount of grammatical cleanup, enhance some explanations

---

book/07-git-tools/sections/rewriting-history.asc

Rewriting history: Minor cleanups; update "git rebase -i" menu

---

book/07-git-tools/sections/reset.asc

In addition to some semantic tidying up, de-capitalize the terms
"index" and "working directory", as those terms are not normally
capitalized in the official Git docs.

Reset demystified: Some semantic cleanup, and much de-capitalization

---

book/07-git-tools/sections/revision-selection.asc

Revision selection: Couple minor clarifications and updates

---

book/06-github/sections/2-contributing.asc
book/10-git-internals/sections/refspec.asc

#1198 with some suggestions. /cc @aollier

Fetch push suggestions

---

book/06-github/sections/2-contributing.asc
book/10-git-internals/sections/refspec.asc

Added a section that explains how to fetch from one repository and to push to another one.

fetch and push with different repositories

---

.tgitconfig

TortoiseGit config: For security, make the parenthesis non-capturing.

TortoiseGit bug tracker

---

book/01-introduction/sections/about-version-control.asc

use of the superlative for RCS

---

A-git-in-other-environments.asc
book/A-git-in-other-environments/sections/sublimetext.asc

Hi @ben,
I've added a section on Sublime Text. This pull-request would help with a part of issue #1205.
To clarify: you can't do any git operations from within the text editor alone, that's reserved for the Sublime Merge git client. There are hooks into Sublime Merge from within Sublime Text so that some git commands can be done, this requires that Sublime Merge is installed of course.
Maybe a section on Sublime Merge would be handy in the "Graphical Interfaces" part of the Git Pro book? Maybe Gitkraken can be mentioned in that same section? It might be duplication of effort, there are lists of git gui interfaces out there on the web. So I'll leave that up to you to decide. :+1: 
---
Hi @wbond,
Thanks for making Sublime Text 3, and thanks for making the git integration in the editor. I …

Sublime Text 3.2 git integration documentation.

---

book/01-introduction/sections/help.asc
book/01-introduction/sections/installing.asc

@ben
Here's the http -> https fix for chapter 1.
- I noticed some links were redirecting to a new website, so I've changed those links.
- I've removed the trailing / at the end of the urls.
I've build the .html files locally from the .asc files, they looked good.
Fixes part of #1210

Chapter 1 http -> https

---

book/01-introduction/sections/help.asc

@ben Git 2.19.1 on Ubuntu 18.10 has more output when using ``git add -h``.
Is this something you want to merge into master? I don't know what version of git the book is based on?

Git version 2.19.1 has new expanded output for git add -h

---

A-git-in-other-environments.asc
book/A-git-in-other-environments/sections/visualstudiocode.asc

This is a initial draft of the Visual Studio Code section. I haven't used this myself, so if checked the official docs, and listed the main features. I've linked the official docs.
I don't think a play by play description/tutorial of how the git integration in Visual Studio Code works is necessary, and it will only become out of date as Visual Studio Code is updated.
Fixes part of #1205

Visual Studio Code git integration documentation.

---

README.asc

I noticed that the README.asc file still points to a http link instead of a https one. This is fixed with this pull request.

Change README.asc to use https link for the book.

---

book/04-git-server/sections/smart-http.asc

@ben
Onwards to Chapter 4, I'm skipping chapter 2 and 3, because I found no mention of http:// in there.
I only found one relevant link that points to a third party http source. So I've updated that link.
The other mentions were in the gitlab.asc and gitweb.asc files, and those links mention user owned hosted servers (Gitlab or GitWeb), so those can stay in http I think?

Chapter 4 http -> https.

---

book/05-distributed-git/sections/contributing.asc

I found only one link pointing to a http:// source, I changed it to https.

Chapter 5 http -> https.

---

book/06-github/sections/3-maintaining.asc
book/06-github/sections/5-scripting.asc

@ben
Regarding book/06-github/sections/3-maintaining.asc:
According to the curl documentation, curl can use https now, so this should work I think. But I don't use curl, so I don't know if this breaks the example.
---
Regarding  book/06-github/sections/5-scripting.asc:
The changes are quite simple here, java uses https for their website, as does github. So I've changed those links.

Chapter 6 http -> https.

---

book/09-git-and-other-scms/sections/client-bzr.asc
book/09-git-and-other-scms/sections/client-tfs.asc

@ben My observations while fixing chapter 9:
---
client-bzr.asc:
Bazaar still uses http:// for their website...
---
client-hg.asc:
Mercurial still links to the http selenic repo when cloning, this is even mentioned in their own wiki, so this can stay.
---
client-p4.asc:
I don't know anything about perforce, so I'm not touching things here.
https://www.perforce.com/products doesn't list Git Fusion anymore, is this still relevant? Git Fusion is not EOL, as can be seen here: https://www.perforce.com/maintenance-support#eol_schedule
---
client-svn.asc:
I don't know anything about Subversion, so I'm not touching things here.
---
client-tfs.asc:
Changed Visual Studio link.
---
import-svn.asc:
I don't know anything about Subversion, so I'm not touching things here.
---

Chapter 9 http -> https. 

---

book/08-customizing-git/sections/attributes.asc
book/08-customizing-git/sections/config.asc

@ben 
I'm skipping chapter 7, I found no http:// links there.
I found a http:// link at book/08-customizing-git/sections/attributes.asc:
>First, you'll need to install `docx2txt`; you can download it from http://docx2txt.sourceforge.net[].
I'm not sure if this should be replaced or not. I've found this: https://sourceforge.net/projects/docx2txt/ but I don't know if that is the proper replacement for it...

Chapter 8 http -> https.

---

book/A-git-in-other-environments/sections/guis.asc

The visual studio sections needs a major rewrite anyways, so I'm leaving it alone.
Zsh still uses the http link mentioned, so no need for change there.

Chapter A-git... http -> https.

---

CONTRIBUTING.md

This link is outdated, using it redirects to the new domain: https://www.sketchapp.com/
By the way, it appears Sketch is now on version 52, according to https://www.sketchapp.com/

contributing.md has outdated link which redirects to new domain.

---

book/B-embedding-git/sections/jgit.asc
book/B-embedding-git/sections/libgit2.asc

@ben can you check that you agree with the changes made in ``book/B-embedding-git/sections/libgit2.asc`` specifically the change of the libgit2 link on GitHub?

Chapter B-embedding-git http -> https.

---

TRANSLATING.md

Hi @ben,
I took the liberty of starting a major rewrite of TRANSLATING.md
1. Changed table to proper GitHub Flavoured Markdown format. (I had problems getting the table to behave after my edits, so I rewrote it in proper GFM).
1. Added new table with the three stages a translation can be in.
1. Rewrite of the Travis CI sections.
1. Removal of Beyond Git (I don't think a section on hacking on git should be in a file about translating.)
1. General cleanup of text.
1. Changed some header text.
1. Changed header level.
Maybe the Travis section can be made clearer? Maybe you have some suggestions on this? You use the system daily I think... :smile: 
And of-course I would like some feedback on the style/content of this rewrite.

Major rewrite of TRANSLATING.md

---

TRANSLATING.md

@jnavila @ben
I've reinstated the old section about "Beyond Pro Git" to the end of the file.
Sequence of events:
* Made a new branch based on master
* ``git checkout 039fe2a934ae19b7d0c45599fc8662c588de9b61``
* Opened translating.md
* Manually copy the section Beyond Pro Git
* Made a new branch to rollback based on master
* Manually pasted the Beyond Pro Git section into master/translating.md
I think/know that this way is probably not the best way of rolling things back (essentially I just manually undid the work).
Also I'm not sure what you're supposed to do once changes are merged into master, I know not to use git --rebase on things that you've pushed, because that annoys everybody, because you re-write history under their feet?
I'm not sure how this rollback could be done cleaner. …

Reinstate Beyond Pro Git section.

---

book/05-distributed-git/sections/contributing.asc

Fix #1217
Changes:
- Fix quote, it now uses the full proper quote. 
- Fix layout of the text, so it's equal to the blogpost.
- Squash 3 lines to use the one line from Tim Pope's blog.

Fix Tim Pope blog quote.

---

book/01-introduction/sections/first-time-setup.asc

Show settings and additional information.

---

book/03-git-branching/sections/basic-branching-and-merging.asc

Closes #609 
See: https://github.com/progit/progit2/issues/609#issue-151535103

Agile/scrum user-story fix.

---

book/04-git-server/sections/git-daemon.asc

Ubuntu 14.04 reaches End of Life this month, upstart is also old. (See: https://www.ubuntu.com/about/release-cycle)
I'm not sure about the:
>On other systems, you may want to use `xinetd`, a script in your `sysvinit` system, or something else -- as long as you get that command daemonized and watched somehow.
section so I'm leaving that in.

Remove ubuntu 14.04 and upstart.

---

book/02-git-basics/sections/undoing.asc

1. Avoid awkward idiom, as discussed in https://github.com/progit/progit2/pull/1179#issuecomment-468422175.
2. Fix pronoun: As it was written, 'it' would've referred to the subject of the sentence, 'changes'. Besides the singular-plural disagreement, it should've said the _file_ was replaced, not the changes.

Reword sentence about losing local changes

---

book/03-git-branching/sections/nutshell.asc

Hi @ben, this is the pull-request you asked for at issue #590.
This implements the proposal made by @YueLinHo.
Closes #590

Fix ambiguity around tree object.

---

.github/ISSUE_TEMPLATE/bug_report.md

:construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: :construction: 
Hi @ben, @schacon, @jnavila,
I think that there is a lot to be gained by adopting templates for bugs/features/pull-requests.
I'll explain why I think this is a good idea below.
I think helping contribute to a project should be easy and clear. Templates are a good way to achieve this. A template can have helpful guidance and a checklist of common pitfalls/errors. If contributors follow the checklist, and follow the template, they should end up with a good bug report/feature request/pull request. This takes the guesswork out of contributing.
During my efforts to clean up the old …

Add a bug report template. (DO NOT MERGE)

---

book/10-git-internals/sections/objects.asc

From my point of view we should note here that a commit object
contains its parent commit(s)

Add extra notes about format for a commit object

---

book/10-git-internals/sections/refs.asc

I'd like to add some notes about the HEAD file content which I think
should be in this book section.
Unfortunately I'm not English native speaker so please correct me if I
did grammar or other mistakes.

Note about SHA-1 values in the HEAD file

---

book/01-introduction/sections/help.asc

Recently I found the extra way to get the manpage so I'd like add it
to the book.

Extend the git commands list to get the manpage

---

book/05-distributed-git/sections/maintaining.asc

Reverts #1252
Previous text (c5689622683df636c92a6138fd0c4c6e45bdc2fe) was correct.
The pull request being reverted applies the meaning of `..` and `...` as
used in revision ranges for `git log` to `git diff`. The later does not
receive revision ranges as a parameter - as can be seen in the manual:
> git diff [--options] \<commit\> \<commit\> [--] [<path>...]
>   This is to view the changes between two arbitrary <commit>.
>
> git diff [--options] \<commit\>..\<commit\> [--] [<path>...]
>   This is synonymous to the previous form. If <commit> on one side is omitted, it will have the same effect as using HEAD instead.
>
> git diff [--options] \<commit\>...\<commit\> [--] [<path>...]
>   This form is to view the changes on the branch containing and up to the second <commit>, starting at a …

Revert Pull Request #1252

---

C-git-commands.asc
book/01-introduction/sections/first-time-setup.asc

Close #1269.
I have not tested most these commands, except for Atom & Sublime and am not sure about:
Maybe worth discussing, besides reviewing the commands:

Aggregate core.editor command list in Appendix C

---

book/07-git-tools/sections/reset.asc

I would like to propose to specify the exact branch the HEAD points
to after the git init command invoking.

Specify the branch the HEAD points to on init

---

book/07-git-tools/sections/rewriting-history.asc

The commits will be rewritten only when the todo list is modified.
Fixes #1277

Running "git rebase -i HEAD~3" won't always rewrite commits

---

images/advance-master.svg
images/advance-testing.svg
images/areas.svg
images/centralized.svg
images/deltas.svg
images/distributed.svg
images/local.svg

customized color scheme that better matches the former look

files checked and corrected

---

book/07-git-tools/sections/submodules.asc

This PR adds 3 useful details about submodules : 
- Mention of `git submodule update --init --recursive`
- Mention of `git checkout --recurse-submodules`
- Add a section about the need to do `git submodule update` after doing `git pull` to finalize the  superproject update if the recorded submodule commit changed.
- Also mention `git pull --recurse-submodules` in this new section

Add practical details about submodules usage

---

book/B-embedding-git/sections/libgit2.asc

the example use of git_repository_set_odb was wrong on the document. It requires repo as input, but was missed.

git_repository_set_odb call needs repo as input

---

book/01-introduction/sections/help.asc

Only the short `-h` option shows the concise help output; the long `--help` option actually opens the manpage, as mentioned at the beginning of the "Getting Help" section. 
This PR fixes the inconsistency in the text.

Getting Help: fix inconsistency with '-h' option

---

C-git-commands.asc

This pull-request changes:
- Add tip about abbreviating long git options to the beginning of Appendix C.
Fixes #1315

Add tip about abbreviating long git options

---

book/09-git-and-other-scms/sections/client-tfs.asc

This pull-request changes:
- Change links to codeplex to point to the archival pages.
- Add caution about git-tf being End-of-Life.
I think this section needs more work though, I would advocate to remove the git-tf part wholesale.
Git-tf clone from codeplex.com will also not work anymore I think.
But a big removal like that is up to @ben and team to decide. 😄 
Related: #1304

Add caution git-tf EOL, change links to Codeplex

---

book/01-introduction/sections/installing.asc

We don't need to run command
```
$ sudo apt-get install getopt
```
because `getopt` already installed on Debian-based systems (as mentioned above).

Remove redundant command

---

book/03-git-branching/sections/rebasing.asc

The phrasing in a warning was confusing.

Correct confusing grammar

---

Gemfile

This commit updates Gemfile to use the latest version of gems and makes a problem with `bundle install` disappear:
```console
$ bundle install
Fetching https://github.com/asciidoctor/asciidoctor-epub3
error: cannot open .git/FETCH_HEAD: Permission denied
Retrying git fetch --force --quiet --tags "/home/<user>/.bundler/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18" due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git fetch --force --quiet --tags "/home/<user>/.bundler/cache/git/asciidoctor-epub3-3986efa04ab5fd28abe5678d7e330e173e425f18"` in directory /usr/share/gems/bundler/gems/asciidoctor-epub3-c8ca2e297cd1 has failed.
If this error persists you could try removing the cache directory …
```

Gemfile: stable version with latest version of gems

---

.dependabot/config.yml

This is a initial dependabot config for the ProGit2 project.
There are some important choices to make:
1. How often should dependabot check for non-security updates? Live/daily on weekdays/weekly/monthly? *Security updates are always created as soon as possible.*
2. Should there be a default reviewer?
3. Should the dependabot pull-request have a GitHub label?
4. Dependabot can automatically merge a pull-request if the Travis CI is okay. Is this something you want?
---
What the current config will give you:
- Live updates for non-security updates.
- @ben is the default reviewer and will thus get a email/notification from Dependabot whenever there is a new update.
- The pull-request that dependabot opens will have the label: "dependabot". This label will need to be created.
- Dependabot …

Create initial dependabot config

---

Gemfile

using asciidoctor version > 1.5.6.2 makes cross-reference links not work

asciidoctor version downgrade

---

book/07-git-tools/sections/rewriting-history.asc

This commit adds:
- a caution block in the relevant part of the book.
- a link to the repository/documentation.
Context:
The git-scm reference documentation for `filter-branch`
warns against using `git filter-branch`,
and recommends using `git filter-repo`.

Add caution: use `git filter-repo` instead of `git filter-branch`

---

book/04-git-server/sections/protocols.asc

As it was, the parts of the sentence didn't quite agree with each other. Adding "HTTP" alongside "HTTPS" restored the agreement that I suspect the sentence originally had.
Also, I changed "these ports" to "their ports" because the specific ports that the protocols use aren't mentioned. "These ports" seems to refer to ports that were previously mentioned in the text; "their ports" intends to refer to the ports belonging to the protocols.

A missing word and a clarification

---

book/03-git-branching/sections/basic-branching-and-merging.asc

I suspect it's clearer to talk about issues instead of tickets. Everyone knows what an issue is. Not everyone has worked with a ticket system; maybe they'll wonder if tickets are part of git. Sticking to the word "issues" seems to allow us to lose no clarity while reducing the chance for confusion.
I'm willing to consider other opinions, however.

Replace mention of "ticket" with "issue"

---

book/03-git-branching/sections/nutshell.asc

I'm reading the book for the first time. I found something confusing so I've added what I hope is a helpful note.
I found it confusing when I tried to use `git log` to replicate what is shown in the graphic (named "HEAD moves when you checkout"); I thought I would see both the "testing" and "master" branches, like in the graphic, but was only able to see "master".
If I've said something incorrect in my note, feel free to change it or let me know how I can improve it—like I mentioned, I'm just reading the book for the first time—I'm happy to incorporate the advice of those wiser than I.

Add note: `git log` doesn't show upstream branches

---

Rakefile

This parameter required to create a single portable HTML file during the build ([source](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images))
Release script already fixed [here](https://github.com/progit/progit2-pub/pull/6)

Include images into HTML file

---

book/10-git-internals/sections/refspec.asc

The docs were saying that partial glob patterns are unavailable in
refspec, and namespacing is the only way to get flexible refspecs
matching multiple branches. This is no longer true since Git 2.6.0 which
added support for partial globbing patterns.
The outdated paragraph was changed so that it now explicitly states that
the approach works.
Closes #1395.

(#1395) Partial globbing is available in refspec since git 2.6.0

---

book/B-embedding-git/sections/go-git.asc

You can read about the project status at: https://github.com/go-git/go-git/wiki/go-git-has-a-new-home!-v5-and-some-explanations

Update go-git URL in Appendinx B: embedding

---

C-git-commands.asc

Since both versions use the same CLI call, I think it would be good SEO to spell out both their official names here ;-)

Clarify meaning of "VS Code"

---

C-git-commands.asc

I'm not entirely sure about this. Maybe `\` everywhere would be less confusing for Windows users?
However, both the Git Bash and cmd.exe seem to accept both versions, at least on my Win10.

Harmonize slashes as backward all Windows paths

---

images/areas.svg

The image at https://git-scm.com/book/en/v2/images/areas.png labels the first box in the upper left "Working Directory". However, all over the text, including the image caption at https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F, the term "Working tree" is used.
I don't know how to regenerate the png, any hints?

replaced 'Working Directory' with 'Working Tree', as per general terminology

---

book/10-git-internals/sections/transfer-protocols.asc

It currently says (emphasis mine):
> Each line starts with a 4-character hex value specifying **how long the rest of the line is**.
> Your first line starts with 00a5, which is hexadecimal for 165, meaning that 165 bytes remain on that line.
This is inconsistent with the examples; the length seems to include its own 4 characters, and the linefeed:
~~~ js
line = '003fe2409a098dc3e53539a9028a94b6224db9d6a6b6 refs/heads/master\n'
line.length === 0x3f
~~~

Error when describing the Smart Protocol?

---

book/07-git-tools/sections/submodules.asc

Fix AsciiDoc `source,console` block to render separately the consecutive commands `git branch try-merge c771610` and `git merge try-merge`. This is accomplished by separating the commands with an empty line, and by omitting the unneeded "(DbConnector) " prefix in front of the `git merge...` command prompt. Puts the example into the form consistent with the other command blocks, and also enhances readability.
State explicitly in the prose that "try-merge" will be the name of the branch.

submodules.asc: clarify DbConnector/try-merge example

---

book/10-git-internals/sections/objects.asc

Add note about commit objects not being reproducible

---

book/02-git-basics/sections/tagging.asc

Fix information about pushing only annotated tags
Github issue #1426

fix outdated information about pushing tags

---

book/07-git-tools/sections/rewriting-history.asc

The first commit in the rebase script `f7f3f6d` should be unmodified after the script is complete
fixes #1431

fix 'Splitting a Commit' rebase bug

---

book/05-distributed-git/sections/distributed-workflows.asc

Add link to Martin Fowlers git patterns page

---

book/10-git-internals/sections/objects.asc

Hi, first time contributing so please bear with me if I missed something.
When testing out some code based on the contents of the internals section, I believe I ran into a small mistake. The header should contain the size in bytes of the content, but `content.length` in the example returns the number of characters. Using `bytesize` returns the right value: https://ruby-doc.org/core-2.4.0/String.html#method-i-bytesize
The example works with its content (`what is up, doc?`) but the issue manifests with other characters 
```ruby
irb(main):002:0> content = "i have €5 in my pocket"
=> "i have €5 in my pocket"
irb(main):003:0> content.length
=> 22
irb(main):004:0> content.bytesize
=> 24
irb(main):05:0> sha_w_length = Digest::SHA1.hexdigest("blob #{content.length}\0" + content)
=> …
```

fix content length calculation in git objects blob header

---

book/01-introduction/sections/first-time-setup.asc
book/02-git-basics/sections/getting-a-repository.asc
book/02-git-basics/sections/recording-changes.asc
book/02-git-basics/sections/remotes.asc
book/05-distributed-git/sections/contributing.asc
book/06-github/sections/1-setting-up-account.asc
book/07-git-tools/sections/reset.asc
book/07-git-tools/sections/submodules.asc
book/07-git-tools/sections/subtree-merges.asc
book/08-customizing-git/sections/config.asc
book/09-git-and-other-scms/sections/client-bzr.asc
book/09-git-and-other-scms/sections/client-hg.asc
book/10-git-internals/sections/environment.asc
book/A-git-in-other-environments/sections/guis.asc
book/A-git-in-other-environments/sections/sublimetext.asc
book/A-git-in-other-environments/sections/zsh.asc
book/B-embedding-git/sections/libgit2.asc

@ben can you review this pull request, also?
Closes: #1443

Move period mark after parentheses

---

book/07-git-tools/sections/rewriting-history.asc

- Create a new section in the book with a link to git-rebase.io
- Closes #1247
- Closes #1329
Pro:
- We skip the work of creating a new tutorial/sandbox for `git rebase`.
- No maintenance costs for maintaining a separate guide.
- The linked guide contains instructions on setting up a 'sandbox environment', where users can just noodle around and learn how `git rebase` works in depth.
- I think that after reading the guide, users will be equipped to use `git rebase` in their own workflow effectively.
Con:
- We have no control over the editorial tone of the guide.
- The site might go down/go out of date.
- Content of the guide is not saved in our own repository.
I've had a lot of time to learn and use `git rebase`, and have opened some (lengthy) issues in the past (#1247 and #1329) on how to …

Create note with link to git-rebase.io

---

book/02-git-basics/sections/viewing-history.asc

Another good finding by @mo-gul: currently, everything related to `--pretty` is called option. This is not ideal for distinguishing the option from its values and the format specifiers. To resolve, I suggest the following naming scheme:
- Option: e.g. `--pretty`, `--stat`
- Option value: e.g. `short`, `full` after `--pretty=`
- [Format specifier](http://www.cplusplus.com/reference/cstdio/printf/): e.g. `%H`, `%T` in `--pretty=format:""`
I've implemented my suggestion for the section related to `--pretty`. I didn't check the entire book; we might want to align other places for consistency.

Replace 'option' by more specific terms where needed for 'git log --pretty'

---

book/05-distributed-git/sections/maintaining.asc
images/large-merges-2.svg

Fixes #1447 
Ok. So, I've updated references of 'pu' to 'seen'. I've mentioned that it was previously called 'pu' in one place as it has served the Git community for 15 years. So, I think it deserves a mention for some more time.
There are still 2 references to 'pu' left:
1. The following reference in the "Long-running branches" section of Chapter 3 "Git Branching".
> Some larger projects also have a `proposed` or `pu` (proposed updates) branch that has integrated branches that may not be ready to go into the `next` or `master` branch.
I'm not particularly convinced about changing that as its not a direct reference to the Git project's branch. 
2. In 'images/merging-workflows-2.png'. This one is a direct reference to the Git project's branch and should be changed. I'm not sure how to go …

Change references of 'pu' to 'seen'

---

book/A-git-in-other-environments/sections/visualstudio.asc

The link that's changed in this commit is dead.
I went to: https://docs.microsoft.com/en-us/visualstudio/windows/?view=vs-2019
to see where the docs for using git with the current version of Visual Studio 2019 can be found.
The site has a section with tasks, when I click on Version control, it takes me to:
https://docs.microsoft.com/en-us/azure/devops/repos/?view=azure-devops
On the azure dev-ops page they have a section called **Get started with Git or GitHub**. That section contains information about using git with Visual studio or from the command line. 
Those sections look like this:
https://docs.microsoft.com/en-us/azure/devops/repos/git/gitquickstart?view=azure-devops&tabs=visual-studio
I'm not sure what the best way to deal with this is, or what the best link should be. I've just …

Change dead link within section on git within Visual Studio

---

book/02-git-basics/sections/remotes.asc

From git version 2.27 onward `git pull` will give a warning if the pull.rebase variable is not set.
You can stop git complaining on every pull by setting the variable.
This pull-request adds a note with help on how to set the variable.
This new behavior for git is documented in the release notes for git 2.27:
https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.27.0.txt
---
I checked the book for the first occurrence of `git pull` and put the note there.
If there's a better place for the note, please say so, and I'll move the note to that place instead. 😄

Add note: how to set the pull.rebase variable

---

book/07-git-tools/sections/submodules.asc

Two trailing spaces to remove.

removes trailing spaces

---

book/07-git-tools/sections/rewriting-history.asc

The example commit `f7f3f6d Change my name a bit` had a different message in one of the sections

Make commit name consistent

---

book/03-git-branching/sections/rebasing.asc

This sentence was too long, and was hard to understand.
I've rewritten this sentence to be clearer, and still say the same thing.

Rewrite overly long sentence

---

TRANSLATING.md

Clicking the old link redirects you to the link that's in this pull-request.
This pull-request replaces the old link with the new link directly, instead of relying on the redirect.

Change link to GitHub docs

---

book/04-git-server/sections/generating-ssh-key.asc

The domain for the GitHub docs has moved to `docs.github.com`.
Following the old link redirects to the [general SSH help page](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh), instead of a page specific to generating the SSH key.
This pull-requests makes the link point to the specific help page on "Generating a new SSH key and adding it to the ssh-agent".

Change link to ssh key generation guide

---

book/01-introduction/sections/first-time-setup.asc

From Git 2.28 onwards you can change the default branch that Git will create when making a new repo with `git init`.
This pull-request adds a section in the first-time-setup part of the book, explaining how to set a different default branch.
I've chosen to use _main_ in the text, as that is what GitHub/Gitlab, and probably us as well, will be migrating towards.
Merging this pull-request also helps with https://github.com/progit/progit2/issues/1462#issuecomment-658827236
**EDIT:**
I did a search for mentions of `git init`, and found multiple places where we could/should reference this new section on changing the default branch name. I'm not sure where I should put links though...

Create section: your default branch name after git init

---

CONTRIBUTING.md

Changes:
- Use the active voice where possible.
- Use a clear title for the licensing section.
- Break up a long sentence in the large rewrite section.
- Remove the word please, when we actually require something from a contributor.
- Use simpler English words
- Remove newline

Improve text of the contributing guide

---

book/01-introduction/sections/first-time-setup.asc
book/08-customizing-git/sections/config.asc

Hi @ben, you wanted a PR for this issue (see your comment at https://github.com/progit/progit2/issues/506#issuecomment-172652988), but the user has not responded in 4 years.
The issue is still present in the book, so I'm fixing it myself.
I hope this is right, please check my work. 😄 
The scope of the fix expanded beyond the one change that you wanted in #506, because multiple parts of the book reference /etc/gitconfig.
Changes:
- Change /etc/gitconfig into [path]/etc/gitconfig
Merging this pull-request closes #506

Change /etc/gitconfig -> [path]/etc/gitconfig

---

book/05-distributed-git/sections/contributing.asc

- Add tip with a link to https://git-send-email.io/ in the _Contribution to the Public Project over Email_ part of the book
This website gives help on configuring your system (what packages to install on your Linux distribution), tells you how to configure your email client, and has a "sandbox repo" that you can target for your very first Git email patch. There are also extra tips and tricks.
I think this is a good match for what this section of the book is about. First you explain the high level overview of how things work, and give some examples in the book. And then the reader can read the tip, go to the website and give the whole shebang a try.
I think this section of the book makes the most sense. I you disagree, feel free to tell me where you want this tip, and I'll move it.

Add tip section with link to git-send-email.io

---

book/03-git-branching/sections/branch-management.asc

An unordered list without a leading blank line renders only as an inline text. Adding a new blank line is enough to make it render properly as an unordered list, as intended.
- Add a new blank line in front of the unordered list to make it render properly.
- None.

Fix unordered list to render properly

---

book/01-introduction/sections/what-is-git.asc
book/03-git-branching/sections/nutshell.asc

[Section 3.1, "Branches in a Nutshell"](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell) talks about snapshots and hashes, and refers to [this page](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control) for more info on them. These topics don't appear on that page however. The author is probably referring to [section 1.3, "What is Git"](https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F). This page is from the same chapter as is currently linked, but I think a more precise link would help the casual reader more.
This PR changes the link to point to section 1.3, "What is Git", instead of to the entire chapter, which takes the reader to section 1.1, "About Version Control".
- Add ID (`[[_what_is_git]]`) to section 1.3
- Link to this ID in …

Link to more precise "What is Git" page in section 3.1 ("Branches in a Nutshell")

---

book/02-git-basics/sections/tagging.asc

- Update Git's detached HEAD help message, as it now uses `git switch` instead of `git checkout` to help users get back to a previous HEAD state.
From at least Git version 2.25.1, the detached HEAD advice text is changed. It now uses `git switch` instead of `git checkout`.
I searched for `detached HEAD` in the whole book and this is the only place where the Git command-line output is shown.
After merging, this would be the only place in the book where `git switch` is used.
@ben, do you want me to make a pull-request for a section explaining `git switch`?

Update Git's detached HEAD help message

---

book/02-git-basics/sections/tagging.asc

- Add v before version number for consistency
Throughout the tagging section we prepend any version numbers with "v", this commit ensures that we're consistent throughout. This also closes issue #852 that found some inconsistencies with the way we use tags.
Fixes #852

Add v before version number for consistency

---

book/01-introduction/sections/what-is-git.asc
book/03-git-branching/sections/nutshell.asc

Implementation of https://github.com/progit/progit2/pull/1506#issuecomment-683137148

Fix internal link error of #1506

---

book/03-git-branching/sections/branch-management.asc

- Fix invalid style for listing a caution block
I created the section on how to migrate a branch from `master` to `main` in  #1476, and added a caution block. I did not use the correct style of block, therefore the caution block was not rendering properly. This pull request fixes the issue.
Also I have now been able to get the Asciidoctor toolchain working! So I have actually verified this myself on the .html and .pdf output. :tada: :clinking_glasses: :partying_face:

Fix invalid style for listing caution block

---

README.asc

- Add new sentence explaining missing .mobi builds.
- Remove .mobi from list of output files
- Remove .mobi from bundle exec rake book:build example
I think it's good to mention that we are not building any .mobi (Kindle) files directly in the readme. That way new contributors are not confused when they try to do the listed commands, and don't get the .mobi output files.
Related issue: #1496, and related pull: #1497.

Explain missing .mobi builds in readme

---

book/07-git-tools/sections/revision-selection.asc

- Add note on escaping curly braces in PowerShell when doing revision selection
I've been struggling with the revision selection syntax `HEAD@{...}` and finally found out it's because of curly braces special meaning in PowerShell. 
I noticed the NOTE on special handling of caret in cmd.exe on Windows. A similar note about curly braces in PowerShell would have saved me some time and I hope to save fellow developers some time by adding in such a note.

Add note on PowerShell in Revision Selection 

---

book/08-customizing-git/sections/hooks.asc

- Add tip: use verbose CLI flags for shared scripts
Implements one of the wanted changes for issue #720:
> Put a note somewhere which says "if you're writing a script that others will need to read, prefer the long versions of command-line flags; six months from now you'll thank us."

Add tip: use verbose CLI flags for shared scripts

---

book/02-git-basics/sections/undoing.asc

- Create section on `git restore`
Fixes #1487 as we now have a section explaining what `git restore` is.
Read #1487 for the discussion we had leading up to this pull request.
This issue is also related:  #1441 but I'm not closing it with this pull, because that issue also talks about the `git switch` command, which this pull request does not add.
This is a rough draft, that basically copies the two undo sections that used `git reset` and replaced the examples with `git restore`.
I'm of course open to your feedback to improve the text. You always have great suggestions! :smile: :+1: 
---
Should we perhaps change the example a bit more, so that we have less of a deja-vu experience? Or would that confuse readers even more?
I feel what I have now is quite heavy, and duplicates a lot of stuff. …

Create section git restore

---

book/02-git-basics/sections/viewing-history.asc

Signed-off-by: Junjie Yuan <yuan@junjie.pro>
- add example for "git log -- path"
```text
diff --git a/book/02-git-basics/sections/viewing-history.asc b/book/02-git-basics/sections/viewing-history.asc
index 0c3b796..72a5117 100644
--- a/book/02-git-basics/sections/viewing-history.asc
+++ b/book/02-git-basics/sections/viewing-history.asc
@@ -262,7 +262,12 @@ $ git log -S function_name
The last really useful option to pass to `git log` as a filter is a path.
If you specify a directory or file name, you can limit the log output to commits that introduced a change to those files.
-This is always the last option and is generally preceded by double dashes (`--`) to separate the paths from the options.
+This is always the last option and is generally preceded by double dashes (`--`) to separate …
```

add example for "git log -- path"

---

book/03-git-branching/sections/nutshell.asc

- Add note about `git switch`
Fixes #1515
Related issues: the `git switch` command was also discussed in #1441 and #1084.

Create note for `git switch`

---

book/06-github/sections/2-contributing.asc

- Add tip to point to the official GitHub CLI tool
Fixes #1530 
The GitHub CLI lets you do your GitHub work from within the command line.
GitHub has just released version 1.0, and so we can "recommend" it to our readers.
I think this is a logical place for the tip. If you want me to move it, let me know. :wink: 
For more information read the [GitHub blog post announcing GitHub CLI 1.0](https://github.blog/2020-09-17-github-cli-1-0-is-now-available/) and go to the [GitHub CLI project page](https://cli.github.com/).

Add tip to point to the official GitHub CLI tool

---

book/02-git-basics/sections/undoing.asc

- Remove the `--staged` flag in the `git restore` warning
It seems like the command that throwing away your local work is `git restore <file>` instead of `git restore --staged <file>`.
See #1533 to get more context.
Fixes #1533

Fix warning about `git restore` command

---

book/06-github/sections/2-contributing.asc

- Fix highlighted text in AsciiDoctor 2 migration branch.
Related to the pull request #1373.
---
---

Fix highlighted text in AsciiDoctor 2 migration branch.

---

book/07-git-tools/sections/revision-selection.asc

Add note that SHA-1 actually has been broken

---

progit.asc

asciidoctor-epub3 1.5.0-alpha-14 and newer now parses whole book as a single document.
Negative leveloffset
1. Breaks appendix hierarchy because Asciidoctor doesn't allow appendix subsections to be higher that level 3. When leveloffset is applied to them, they become level 2 and are no longer children of appendix and instead become standalone chapters
2. Transforms progit into a multi-part book instead of multi-chapter book, what I think is wrong
After removal of negative offset, EPUB is structurally equivalent to other formats.

Stop adding negative leveloffset for EPUB

---

book/02-git-basics/sections/undoing.asc

`git restore` introduced  in v2.23.0

---

C-git-commands.asc

- Removed the erroneous --add parameter from the example core.editor config used for TextEdit.
Fixes #1537

removed `--add` from TextEdit core.editor config

---

book/07-git-tools/sections/revision-selection.asc

- Fixed \`\~\~\~\` presented as subscript tilde.
I noticed that \~\~\~ is presented as subscript tilde on git-scm site for some reason:

Escape tilde to fix HEAD~~~ presented as HEAD~

---

book/07-git-tools/sections/advanced-merging.asc

Asciidoctor documentation suggests solution to properly render a possessive monospaced phrase by using [unconstrained formatting](https://asciidoctor.org/docs/user-manual/#unconstrained-formatting-edge-cases).
However, this approach does not work when one more monospaced phrase follows [in the same paragraph](https://gist.github.com/yugaego/edcef321c3e4a7c4f59d7756d7ef4042).
The simplest workaround was suggested by the Asciidoctor project lead Dan Allen.
**Before:**
PDF
HTML
EPUB
**After:**
PDF
HTML
EPUB

Fix formatting issue

---

book/10-git-internals/sections/refs.asc

When reading this line I was very confused.  It didn't sound like it made sense.  So I checked out a remote ref, ran `cat .git/HEAD`, and lo and behold it did "point" to the same thing that the remote branch pointed to.
I played around with it a little bit more and realized the difference between checking out a local and remote reference is that checking out a local reference sets `.git/HEAD` to a SYMBOLIC ref, while checking out a remote reference sets it to the exact commit.
I think the current language is *technically* correct, because "Git won't point HEAD at one" means it won't point HEAD to the remote reference itself (since "one" means the remote reference, not the commit).  So I'm not saying the current wording is bad, just that it confused me, so it might confuse others
Also, …

Make wording in refs.asc clearer

---

book/06-github/sections/2-contributing.asc

- added the `git fetch <repository>` command before we can use &lt;repository&gt;.
When you fork a repository and want your fork update-to-date, you can add the original repository to the remote list.
But before you can configure your `master` branch follow `<repository>/master` branch, it is required to first fetch the remote to get the `<repository>/master` branch.

fetch original repository before use

---

book/07-git-tools/sections/reset.asc

Fixes the irregular capitalization of "working directory" in "The Workflow" subsection of "Reset Demystified" section of "Git Tools" chapter.

Fix irregular capitalization

---

book/01-introduction/sections/about-version-control.asc
book/02-git-basics/sections/getting-a-repository.asc
book/02-git-basics/sections/recording-changes.asc

- The redundant phrase "VCS systems" should be replaced with "VCSs" in three locations in the text (sections 1.1, 2.1, 2.2).
"VCSs" as a plural abbreviation is established in the Introduction and used elsewhere in the book.

Replace 3 instances of "VCS systems" with "VCSs"

---

book/02-git-basics/sections/recording-changes.asc
book/02-git-basics/sections/remotes.asc

Fix reported typo in Chapter 2 of the book:
1. `merge the remote's master into the local` (#1565)
2. `nothing to commit, working directory -> nothing to commit, working tree` (#1559)
Fixes #1565 
Fixes #1559

Fix reported typo issue in Chapter 2

---

book/02-git-basics/sections/undoing.asc

In file [progit2/book/02-git-basics/sections/undoing.asc](https://github.com/progit/progit2/blob/master/book/02-git-basics/sections/undoing.asc) two dashes were connected in one.
Screenshot:
Decision was found from:
[https://github.com/SergeiKuznetsov/progit2-ru/commit/149801bfcb5a4bda5a324177172325e3b5f95efd](https://github.com/SergeiKuznetsov/progit2-ru/commit/149801bfcb5a4bda5a324177172325e3b5f95efd)

Split of two dashes

---

README.asc
Rakefile

This PR refactors monolithic `book:build` task into several smaller tasks:
1. `book/contributors.txt` file task: generates contributors list required to build book formats
2. `book:build_html` - build HTML format
3. `book:build_epub` - build Epub format
4. `book:build_pdf` - build PDF format
5. `book:check` - check HTML and Epub
This also add convenience tasks:
1. `book:clean` - clean artifacts (contributors list and books)
2. `book:ci` - build books with checking enforced (not ignored), targeted for CI.
Note: The CI doesn't execute `book:ci`, but still running `book:build` instead. Discussions are welcome whether the CI should switch to `book:ci` or not.
Fixes #1595

Refactor book:build task

---

book/02-git-basics/sections/undoing.asc

- updated `Important` note at [Git-Basics-Undoing-Things](https://www.git-scm.com/book/en/v2/Git-Basics-Undoing-Things):
> It’s important to understand that git checkout — <file> is a dangerous command. Any local changes you made to that file are gone — Git just replaced that file **with the most recently-committed** version. Don’t ever use this command unless you absolutely know that you don’t want those unsaved local changes.
> It’s important to understand that git checkout — <file> is a dangerous command. Any local changes you made to that file are gone — Git just replaced that file **with the last staged or committed** version. Don’t ever use this command unless you absolutely know that you don’t want those unsaved local changes.
As it's more precise what's happening when you have …

update important note for git restore & git reset HEAD

---

book/03-git-branching/sections/branch-management.asc

- The branch name should be `monospaced` if it is not a reference to the word.

Update branch name highlight

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml

- Use a `config.yml` file in the `ISSUE_TEMPLATES` folder which adds new buttons with links to the proper place to report certain bugs
- Remove "migrated" lines from the Markdown bug report template
This `config.yml` file adds extra links on the issue select screen on GitHub.
GitHub calls this screen the "issue template chooser".
The contact_links have a name, description and URL property.
[GitHub docs, configuring the template chooser](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)
Example of how the external links look on the screen (ignore the text for now, you can customize this):
See how you get a nice big `Open` button. 😄 
This way we can redirect bug reports that are not for the ProGit …

redirect bugs not for ProGit2 with config.yml file

---

book/05-distributed-git/sections/contributing.asc

- Fix the link to <https://git-send-email.io> to use AsciiDoc syntax instead of Markdown.
Builds on #1489

Fix lingering Markdown for git-send-email.io

---

book/03-git-branching/sections/remote-branches.asc

Fix a index for @{u} and @{upstream} in remote-branches.asc

---

book/01-introduction/sections/installing.asc

This PR removes GitHub Desktop from the installation instructions for getting Git on your machine. 
I'm the engineering manager for GitHub Desktop. We try to avoid confusion from people thinking that downloading Desktop is an easy way to also install Git. There's more context here about why we chose to avoid that for the current version: https://github.com/desktop/desktop/issues/3708#issuecomment-354665183

Remove GitHub Desktop from installing Git section

---

.github/ISSUE_TEMPLATE/config.yml

- Change word `here` -> `there`
I think the current wording is confusing to newcomers to the ProGit2 repository: see #1627.
The user probably meant to post at the Git for Windows repository, but somehow still ended up here. 😄 
We can all take a wrong turn somewhere, but we should still ensure that we're clear on where to go instead.
Feel free to suggest further improvements to the text, maybe we should be really explicit and say:
`Click on the "open" button next to this text to go to the right place to report your problem.`?

Improve wording on issue select screen

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement_idea.md
.github/ISSUE_TEMPLATE/feature_request.md

- Create draft feature request template
- Fix white-space error in bug report template
- Use consistent " quotes in bug report and feature template
- Contributors can no longer open a blank issue on GitHub
- Automatically label incoming features/bugs
Fixes #1606 
---
@ben You probably have feedback for me on this draft.
The main things we probably want to know about a proposed feature are:
- What the feature is going to do.
- What the feature is going to solve.
- Other solutions that might be possible.
- Whether the contributor wants to help out with making the feature.

Create feature request template, improve bug report template, disable blank issues

---

README.asc
Rakefile

- Enable `.mobi` (Kindle) format again
- Add references to mobi files back in README
- Add mobi rake build command to README
Fixes #1528
`asciidoctor-epub3` has the Kindlegen dependency in it again, so we can enable mobi builds again. (https://github.com/progit/progit2/pull/1646#issuecomment-828968577)
Please check if this change alone is enough to get things working.
@slonopotamus @jnavila can you please check my work?

Enable .mobi (Kindle) format again

---

book/10-git-internals/sections/objects.asc

Alert readers who are following along in the shell that the next example does not use the repository that was just created.  
- 
Section 10.2: Git Objects begins with creating a new repository and explaining how blobs are added to it.  The active voice used throughout that section implies it is expected for readers to be following along within their own shell.  The next section, 10.2: Tree Objects, begins with an example which is not related to the previous examples.  The current wording is "most recent tree in **a project** may look something like this".  However, the project created in the previous section is a not a valid interpretation of "a project"; it does not yet have a tree.  As a result, readers may enter the command given into their shell and produce an unexpected result:
``` …
```

Clarify tree object example not a continuation of previous examples

---

Rakefile

- Try to fix the broken `.mobi` build
Should (at least partially) fix my broken PR I made at #1655...

Fix broken .mobi build

---

.github/dependabot.yml

- Check for GitHub Action updates daily (Monday through Friday)
Dependabot can check for GitHub Action runner updates.
You only need this PR **after** you've migrated to GitHub Actions for your CI.
Feel free to close this PR if you decide to migrate to some other CI provider.
Just wanted to get this ready in case it's needed.
Feel free to tell me to tone down the frequency of the checks, I can also use `weekly` or `monthly`.

Check for github-actions updates with Dependabot

---

.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
.github/workflows/pr-build.yml
.github/workflows/release-on-merge.yml
TRANSLATING.md
atlas.json

- Adjust workflow files
- Adjust links in some files on our repo (not strictly necessary, but nice to have anyways)
- Adjust `atlas.json`
- Adjust line in `TRANSLATING.md` that refers to the ProGit2 default branch
Well waiting on this has been very beneficial, as GitHub does most of the hard work automatically now. 😄 
Read the GitHub docs before starting: https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch
Steps to migrate:
1. Review this PR, confirm this contains all the necessary changes in script files/rakefile/action workflow files.
2. Merge this PR.
3. Repository maintainer uses GitHub web interface to rename the `master` branch to `main` following the steps in the GitHub docs.
4. Done.
State of repository after merging …

Migrate from master to main

---

book/B-embedding-git/sections/dulwich.asc

- Due to errors on loading particular webpages from dulwich.io the HTML checker fails on each build. And it's better to use the main page only instead of the list of pages.

Use generic link to Dulwich website

---

book/07-git-tools/sections/credentials.asc

This PR:
1. Update usage snippet for `git credential-read-only` as the credential helper now requires `username` parameter
2. Update code listing explanation to reflect `username` parameter requirement above
Fixes #1375

Update usage snippet and code explanation for git credential-read-only

---

book/07-git-tools/sections/rewriting-history.asc

A small typo fix within the Rewriting History section, changing "they" to "that" in the below sentence:
> To modify a commit that is farther back in your history, you must move to more complex tools. Git doesn’t have a modify-history tool, but you can use the rebase tool to rebase a series of commits onto the HEAD they were originally based on instead of moving them to another one.

Small rewording change inside Rewriting History

---

book/10-git-internals/sections/maintenance.asc

Use -L option in curl command to follow redirect returned by www.kernel.org. Otherwise, the file you are testing with is not the ~5MB git.tgz, but a 168 byte HTML page informing you about the redirect.
Everything under https://www.kernel.org/pub/ seems to 301 (moved permanently) redirect to https://mirrors.edge.kernel.org/pub/. So the other option is to change the URL instead of adding the `-L` curl option. However, the www.kernel.org homepage still links to them as https://www.kernel.org/pub/, so it isn't clear to me what the most stable URL is, which is why I went with the -L.

Use -L option in curl command to follow redirect

---

book/A-git-in-other-environments/sections/bash.asc

- When I followed the instructions with the "Git in Bash" [page](https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Bash), it did not work directly for me. It took me some time to realize -- with the help of <https://stackoverflow.com/a/50919451/5028673>, thanks! -- that when I took the files `contrib/completion/git-completion.bash` and `contrib/completion/git-prompt.sh`, I took them from the `master` branch, while I was running an "older" version of Git. Thus, I was thinking that it would be useful to mention within the instructions to be careful about the version of the source code to use.
See above.

bash.asc | Warn about the version of the source code

---

book/04-git-server/sections/gitlab.asc

- Corrected minor spelling error `an user account` -> `a user account`

Correct spelling error

---

book/07-git-tools/sections/rewriting-history.asc

- Quotation marks style is changed from grave+apostrophe to combination that is properly rendered as slanted double quotation marks as used in other parts of the book.
This is the only place in the book where this type of quotes were used. Also, grave in the Noto Serif font included with EPUB version of the book is combining, so this two words were rendered incorrectly:

Fix quotes in "Rewriting history" section

---

.github/ISSUE_TEMPLATE/bug_report.yml

- Use proper required checkboxes syntax
The old forms are not properly forcing some checkboxes to be ticked before proceeding, this PR makes it so that we properly force the checkboxes. 😄 
Turns out you need to put the `required: true` value under the `option` key, not in a separate `validations` key... 😄 
Example of _invalid_ syntax:
```yaml
- type: checkboxes
attributes:
label: There's no existing/similar bug report.
description: Please search to see if an issue already exists for the bug you encountered.
options:
- label: I have searched the existing issues
validations:
required: true
```
Example of _correct_ syntax:
```yaml
- type: checkboxes
attributes:
label: There's no existing/similar bug report.
description: Please search to see if an issue already exists for the bug you …
```

Use proper required checkboxes syntax

---

C-git-commands.asc

The `-f`/`--nofork` flag is suggested to be used "... when Vim is executed by a
program that will wait for the edit session to finish...." However, this flag
is only used when Vim has the GUI version, effectively no-op'ing when non-GUI
Vim. This mirrors the existing "--nofork" flag for the Windows `gvim` example.
I didn't see any prior issues/PRs related to this flag for `vim`.
This flag did fix a co-worker's issue, referenced in this SO question https://stackoverflow.com/questions/22699614/git-commit-messages-lost-by-vi (I've never personally encountered the issue).
As best I can tell, this flag exists regardless if the user's `vim` features a GUI. To be honest, I'm not clear if the flag does anything for just `vim` and only for `gvim`. 
Basing on …

Add '--nofork' flag to vim example in Appendix C

---

book/10-git-internals/sections/maintenance.asc

commit message in `maintenance.asc` (chapter 10)
"Modify repo.rb a bit" gets used later on in the log outputs for that same commit, so the message should be equal.

Update message to be equal with later mentions

---

book/07-git-tools/sections/credentials.asc

GCM for Windows (along with GCM for macOS/Linux) has been replaced with the cross-platform GCM Core.
Remove mention of "GCM for Windows", replace with "GCM Core".
GCM for Windows has been superseded GCM Core. GCM for Windows is deprecated and no longer supported.

Modernize recommendation for credential store

---

book/02-git-basics/sections/recording-changes.asc

- Adds code highlighting to the `add` and `rm` subcommands when explaining recording changes

Fix add/rm subcommand code highlighting

---

book/10-git-internals/sections/objects.asc

The book clearly mentions that --add needs to be passed to 'git update-index'
only when the file is new to the index. When the second version of 'test.txt' is
added, the index know about the file already.
So, avoid passing the '--add' when adding the second version of 'test.txt'

ch-10: avoid unnecessary mention update-index's --add

---

book/08-customizing-git/sections/attributes.asc
book/B-embedding-git/sections/libgit2.asc

See also:
https://docs.asciidoctor.org/asciidoc/latest/text/troubleshoot-unconstrained-formatting/#unconstrained-edge-cases
https://docs.asciidoctor.org/asciidoc/latest/text/quotation-marks-and-apostrophes/#possessive-monospace
https://docs.asciidoctor.org/asciidoc/latest/text/#unconstrained
Fixes #1644
Uses different quoting style for formatting characters to allow correct escaping and printing. I found occurrences in two places (looking for ``` `'s```).
These were generated using `bundle exec rake book:build_pdf` with `Bundler version 2.3.17` and `ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]`.
**However**, note that the first case with the `export-subst` section is rendered incorrectly on [the website](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes) …

Use unconstrained formatting pairs for possessive monospace

---

book/08-customizing-git/sections/attributes.asc

I just removed one sentence that "comments" on MS Word. Either everybody agrees with the sentiment, making the sentence redundant, or not, making it alienating to some. Author's view is already apparent from the previous sentence. :smiley: 
btw: Thanks so much for a great resource! :clap:

Remove unnecessary dig at MS Word

---

book/08-customizing-git/sections/config.asc

- Adds in-line code markup to the word "input",
as it is mentioned as a setting value.
When mentioning the `core.autocrlf` value `true`, the text marks it up as in-line code.
This patch applies the same markup to the `input` value of the same setting.

Mark up "input" as in-line code

---

book/07-git-tools/sections/submodules.asc

Since f0a96e8d4c (submodule: fall back to remote's HEAD for missing
remote.<name>.branch, 2020-06-24), which went into Git 2.28, 'git
submodule upadte --remote' does not default to using the 'master' branch
of the remote repository, but rather the remote repository's HEAD
branch.
Tweak the wording to reflect this behaviour change.
Noticed while re-reading the chapter today.

Submodules: update `git submodule update --remote` behaviour

---

book/01-introduction/sections/first-time-setup.asc
book/02-git-basics/sections/recording-changes.asc

- Add an id to Ch01 > First-time Git Setup > Your default branch name.
- Add a note in Ch02 > Recording Changes to the Repository > Checking the Status of Your Files, directly after the paragraph that says:
> Finally, the command tells you which branch you’re on and informs you that it has not diverged from the same branch on the server. For now, that branch is always `master`, which is the default; you won’t worry about it here.
The note points out that remote repositories are likely to have a different default branch name.
GitHub in mid-2020 changed the default branch name from `master` to `main`, and so did other Git hosts.
And many developers use an even different default branch name like `dev` or `develop` or something else.
A beginner might be very confused when seeing a repo whose …

Note that master is not always the default

---

Rakefile

This is a bug starting in 2.1.308 (PR #1667). This is due to a missing terminal in GitHub Actions (GHA); reported at [StackOverflow](https://stackoverflow.com/a/43042363) for Jenkins but still relevant for GHA and `git shortlog`.
Update Rakefile
Fixes #1040 (yet again)

Fix missing contributors in GH Actions runs #1040

---

book/07-git-tools/sections/credentials.asc

[Microsoft/Git-Credential-Manager-for-Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) was archived on 2020 Sep 30 and it is no longer being maintained. 
> The cross-platform [Git Credential Manager Core (GCM Core)](https://aka.ms/gcmcore) is the official replacement.
Therefore, I have updated the documentation to reflect this fact and recommend instead that readers rely on  Git Credential Manager Core (GCM Core). 
#736
#583 
#1724

Update instructions for Windows GCM (now mergeable)

---

book/01-introduction/sections/first-time-setup.asc
book/02-git-basics/sections/recording-changes.asc

Rename the anchor ID `[[_default_branch]]` to `[[_new_default_branch]]`, updating the reference
to it.
Fixes asciidoctor build warnings due to pre-existing [[_default_branch]] anchor ID of the same name.
-  Change the anchor ID name and/or reference in:
```
book/01-introduction/sections/first-time-setup.asc 
book/02-git-basics/sections/recording-changes.asc 
```
This clashed with:
```
book/06-github/sections/3-maintaining.asc
```
commit 2af8f742c69c8cfac44ce56e1b51701948be93bc
added a reference `[[_default_branch]]`.
commit 1b64de1eb4023847fe371289ec2ca58ede6902be
adds a links to that reference.
However, the reference already existed in:
```
book/06-github/sections/3-maintaining.asc
```
created in 2014 with:
commit bf7ce71d803a33cf98a347527c9369221040a01c
Rename the new reference to …

Fix clash with named anchor ID

---

book/08-customizing-git/sections/config.asc

- Add a note in 'Basic client configuration' mentioning Conditional includes 
When a user belongs to several organizations they may have different
identities or settings for the repos belonging to each
organization. Conditional include allow to apply those configuration
settings to each group without defining them on each repo
individually.
A big problem with the feature is its discoverability. A brief mention
in the configuration section to check out the details in the
documentation can dramatically raise awareness.
Fixes #1801

Mention includes in configuration section

---

book/01-introduction/sections/installing.asc
book/02-git-basics/sections/viewing-history.asc
book/04-git-server/sections/gitweb.asc
book/04-git-server/sections/protocols.asc
book/05-distributed-git/sections/contributing.asc
book/05-distributed-git/sections/maintaining.asc

Cloning using git:// and running the cloned code is bad if e.g. you are in a public wifi.
Many people don't know that, (including me a few years ago), so I put that in the documentation.

Added warning about the insecurity of git://

---

C-git-commands.asc
book/01-introduction/sections/installing.asc
book/02-git-basics/sections/viewing-history.asc
book/03-git-branching/sections/basic-branching-and-merging.asc
book/04-git-server/sections/gitlab.asc
book/04-git-server/sections/gitweb.asc
book/04-git-server/sections/smart-http.asc
book/06-github/sections/2-contributing.asc
book/07-git-tools/sections/credentials.asc

Changes:
- Add some ending dots.
- Use macOS spelling.
- Capitalize URL occurrences.
- Add some ending dots.
- Use macOS spelling.
- Capitalize URL occurrences.

Fix some spellings

---

book/07-git-tools/sections/advanced-merging.asc

- In previous commits the apostrophe characters were replaced with `'`. This syncs the remaining one.

Sync apostrophe character

---

book/10-git-internals/sections/environment.asc

- Adds a description of the `GIT_SSH_COMMAND` env variable.
Seems when this section was first written, `GIT_SSH_COMMAND` did not yet exist or wasn't as popular as it seems to be now. Especially when handling multiple keys across different git hosting services, it's a convenient way to quickly select the a given key for a given service.

Update ssh env vars description

---

book/01-introduction/sections/help.asc

- There is a new option `--sparse` available for `git add` and the help output here is synced with the new one.

Add new option --sparse to git add help output

---

book/09-git-and-other-scms/sections/client-p4.asc

- Link to Git Fusion has been redirected. I've replaced the link with the Git Fusion manual instead.
- Link to virtual machine has been also redirected in the mean time and now points to downloads instead.
- Download link to p4 tool has been replaced with the Helix command line client p4 link.

Fix link to Perforce tools

---

Rakefile

- Version written in the book was one tag behind the one on the PDF at GitHub releases. Next tag needed to be calculated here.
Steps to reproduce the issue:
- Visit https://git-scm.com/book/en/v2
- Download PDF
- Version in the PDF and the last published tag on the GitHub releases don't match (one patch behind)

Fix the next version calculation

---

C-git-commands.asc

Kate editor must be started with "--block" option so git commit can patiently wait for the editor to close the commit message file.
Fixes #1893

Fix #1893: git commit should be able to wait for Kate editor

---

book/08-customizing-git/sections/config.asc

There is a typo in chapter 8 under core.pager last line, it say 'Git will page'. The word 'page' should be replaced with the word 'print'
- Fixed typo in last line of chapter 8 under core.pager.
- The word "page" is replaced by "print".
Fixes #1925

fixed typo in chapter 8 under core.pager

---

book/04-git-server/sections/gitlab.asc

- [ x] I provide my work under the [project license](https://github.com/progit/progit2/blob/main/LICENSE.asc).
- [ x] I grant such license of my work as is required for the purposes of future print editions to [Ben Straub](https://github.com/ben) and [Scott Chacon](https://github.com/schacon).
The information about admin user and password for a new gitlab installation was outdated, I have changed the information to reflect changes in the self hosted version of Gitlab.
-

Update gitlab admin user and password info

---

book/02-git-basics/sections/remotes.asc

- Replace _in lieu of_ with _instead of_.
While reading the book, I bumped into this "in lieu of" expression, and as a non-native English speaker, I had to google it to understand it.
I think these are the reasons to make this change:
- **consistency**: [this is **the only** place in the book where this expression is used](https://github.com/search?q=repo%3Aprogit%2Fprogit2+%22in+lieu+of%22&type=code), while "instead of" is [used many times](https://github.com/search?q=repo%3Aprogit%2Fprogit2+%22instead+of%22&type=code) (36 at this moment).
- **understandability**: I believe there are (and will be) many non-native English people reading this book, and using a more common expression will make it easier for them to understand the content.

Replace 'in lieu of' with 'instead of'

---

book/07-git-tools/git-credential-read-only

- Modify ruby scripts `git-credential-read-only`: `File.exists?` to `File.exist?`

Modify ruby scripts: File.exists? to File.exist?

---

C-git-commands.asc

- Add a single backslash to the Notepad++ editor path in A3.1 Setup and Config.
It appears that the pair of "++" in the Notepad++ path may be interpreted as an inline passthrough by Asciidoctor. The double pluses are omitted in the rendered text (both on git-scm.com and the .pdf in the latest release.) The resulting command is incorrect if copied and pasted into the terminal, which is exactly what I had done when I noticed the problem.
If GitHub's web editor is rendering my change correctly, a single backslash in the first pair of double pluses is enough to fix the issue. After reading the contributing guidelines, I figured this is a minor enough correction that I did not need to open an issue first, but I have not contributed before. Constructive criticism welcomed. Thank you for your …

Escape notepad++ default installation path

---

C-git-commands.asc

Fix issue 1977

---

book/03-git-branching/sections/remote-branches.asc

Remove the recommendation for `git fetch && git merge` over `git pull`
Fixes #2020

Remove recommendation for git fetch && git merge over git pull

---

book/07-git-tools/sections/debugging.asc

Fix a typo

---

book/01-introduction/sections/first-time-setup.asc

Clarify that --global configuration is not applicable system-wide, but only within the scope of the logged in as current user.
add "while logged in as you"
Configuration via the  `--global` option does not affect everything "on that system". I believe it is limited in scope to the user. This change attempt to make that clear. It could be worded better but I'm struggling to come with anything better than this!

Clarify that --global configuration is not applicable system-wide

---

book/09-git-and-other-scms/sections/client-svn.asc

The wording "rather than treating them remote branches." is missing a preposition "as".
- Fixes a grammatical error in client-svm.asc: "rather than treating them remote branches"

Fix grammar on how git svn fetches tags

---

book/A-git-in-other-environments/sections/jetbrainsides.asc
book/A-git-in-other-environments/sections/sublimetext.asc
book/A-git-in-other-environments/sections/visualstudiocode.asc

- Add index for files in Appendix A
Fixes #1976

Add index for files in Appendix A
